### ISSUE TITLE
Failed to run 'git submodule update --init --recursive'

### ISSUE THREAD

**Issue by woohaha** [listen1/listen1_desktop#1]
Error log:
>listen1_desktop (master*) » git submodule update --init --recursive
> Cloning into 'app/listen1_chrome_extension'...
> Warning: Permanently added the RSA host key for IP address '192.30.252.122' to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:listen1/listen1_chrome_extension.git' into submodule path 'app/listen1_chrome_extension' failed

**Comment by listen1** [comment]
http://stackoverflow.com/questions/3617113/github-permission-denied-publickey-fatal-the-remote-end-hung-up-unexpectedl

如果用这种方式需要设置ssh key，否则出现鉴权错误

**Comment by woohaha** [comment]
Solved. The public key on this Mac was not added to my Github profile.
