### ISSUE TITLE
【bug反馈】歌词滚动显示异常

### ISSUE THREAD

**Issue by KingGeorgeWang** [listen1/listen1_desktop#105]
播放时歌词无法滚动，滚动条也不能拖动。此情况在刚进入软件播放上次歌曲时出现，切换到下一首之后恢复正常。

**Comment by KingGeorgeWang** [comment]
此外，部分时刻会出现歌词自动连续向下滚动的情况（不随乐曲进行，歌词到底后停止），且不能拖动滚动条回到之前的位置。

**Comment by listen1** [comment]
歌词问题已经在v2.17.0版本中修复，谢谢你的反馈
