### ISSUE TITLE
求做一个暗色主题，界面在晚上用有点刺眼。。。

### ISSUE THREAD

**Issue by zhang199688** [listen1/listen1_desktop#107]
求做一个暗色主题，界面在晚上用有点刺眼。。。

**Comment by BingoKingo** [comment]
除了夜间模式外还需要别的主题，可以做一个个性化设置的选项吗？

**Comment by zxjhxjh** [comment]
/* global settings (theme related) */
:root{
    --icon-default-color: #666666;
    --icon-highlight-color: #6f6f6f;
    --text-default-color: #eeeeee;
    --text-subtitle-color: #666666;
    --text-disable-color: #999999;
    --lyric-default-color: #666666;
    --link-default-color: #999999;
    --link-highlight-color: #6f6f6f;
    --line-default-color: #e5e5e5;
    --sidebar-background-color: #1f1f1f;
    --content-background-color: #1f1f1f;
    --foot-background-color: #1f1f1f;
    --search-input-background-color: #222222;
    --window-control-border-color: #dddddd;

    --sidebar-highlight-background-color: #4d4d4d;
    --sidebar-highlight-text-color: #ffffff;
    --important-color: #ff4444;
    --button-border-color: #bebebe;
    --button-hover-background-color: #111111;
    --now-playing-page-background-color: #1f1f1f;
    --now-playing-close-icon-color: #666666;
    --disable-song-title-color: #b7b7b7;
    --windows-border-color: #eeeeee;

    --default-border-radius: 2px;
    --text-default-size: 13px;
    --h2-title-font-size: 24px;
}
试试看把目录里resources/app.asar文件里大概19650行左右对应的这段改成这样，就勉强算暗色主题了。。。播放栏暂时没找到，等大佬补充

**Comment by zxjhxjh** [comment]
[app.zip](https://github.com/listen1/listen1_desktop/files/3173032/app.zip)
解压并替换掉原目录下的app.asar即可

**Comment by listen1** [comment]
已经增加了深空灰模式
