### ISSUE TITLE
致敬“千千静听”，致敬“foobar2000”

### ISSUE THREAD

**Issue by yoramuhoo** [listen1/listen1_desktop#1088]
各种各样音乐播放器被吹的神乎其技，都无一例外的秒删。贵软也一样。致敬“千千静听”，致敬“foobar2000”。Linux下，你能搞定本地lrc歌词就可以成功了，不需要下载。搞懂搞西，你玩不过资本。徒劳无功，浪费时间。

**Comment by PLXT** [comment]
说的对，这种浪费时间的事没钱玩不下去，不然你给他投点钱，要么贡献点代码

**Comment by yoramuhoo** [comment]
> 说的对，这种浪费时间的事没钱玩不下去，不然你给他投点钱，要么贡献点代码
我找到了一个播放器，Quod Libet有个插件叫view Lyrics 可以在播放界面内显示歌词，虽然不能滚动，目前我觉得够用了。歌词的实现是读取音乐本身的内嵌。可以去网站下载歌词再贴入。
1,确实应该鼓励linux平台的软件。网易删歌，QQ受限。大佬都没办法的事情，普通人是搞不了的。普通人搞音乐软件的极限就是本地播放器，聚合音乐，只是碰瓷大佬罢了。只是试听软件，哪个喜欢音乐的，电脑里不躺着几百首歌？我想很多人需要的是，可控的歌词，可以保留在本地，不受软件约束。
2,UI,有玩暴你的，管理有玩暴你的，我不用深度，如果用深度也是可以接受的，毕竟是默认音乐播放器。
3,我给Audacious论坛提议过支持lrc歌词，现在已经可以支持了。也可以镶嵌在界面内，但不滚动。**### 我有打算继续使用Audacious,好吧，我现在就用他了。**Audacious曾经是我最喜欢的音乐软件。所以我认真的给他们留言过。网易和QQ太失望了。所以我在这里留言。
————————————————————————————
投钱，我不会给秒删的软件投钱，网易曾经不错，QQ是秒删，他们不缺钱。如果有人做出linux下的千千静听，如果认可你的人多，也还是有收入的。我不是投资者，自然不会投钱。但作为用户，可以给予小额支持。

贡献代码。我会的话，我选择为Audacious写插件，但我不会写代码。因为Audacious可不是我秒删的软件。
————————————————————————————
一切向钱看，开源环境，国外确实比国内好些。但国内赚的是人民币，都不容易。我也没什么可说的。他们可以用爱发电，国内难。

皮肤，皮肤。千千静听和foobar2000都有很多皮肤，都有滚动歌词。本地歌词可控。所以他们是“神”。其他不要说了，未来是版权时代。

**Comment by yoramuhoo** [comment]
> 说的对，这种浪费时间的事没钱玩不下去，不然你给他投点钱，要么贡献点代码

我找到了一个播放器，Quod Libet有个插件叫view Lyrics 可以在播放界面内显示歌词，虽然不能滚动，目前我觉得够用了。歌词的实现是读取音乐本身的内嵌。可以去网站下载歌词再贴入。
1,确实应该鼓励linux平台的软件。网易删歌，QQ受限。大佬都没办法的事情，普通人是搞不了的。普通人搞音乐软件的极限就是本地播放器，聚合音乐，只是碰瓷大佬罢了。只是试听软件，哪个喜欢音乐的，电脑里不躺着几百首歌？我想很多人需要的是，可控的歌词，可以保留在本地，不受软件约束。
2,UI,有玩暴你的，管理有玩暴你的，我不用深度，如果用深度也是可以接受的，毕竟是默认音乐播放器。
3,我给Audacious论坛提议过支持lrc歌词，现在已经可以支持了。也可以镶嵌在界面内，但不滚动。**### 我有打算继续使用Audacious,好吧，我现在就用他了。**Audacious曾经是我最喜欢的音乐软件。所以我认真的给他们留言过。网易和QQ太失望了。所以我在这里留言。
————————————————————————————
投钱，我不会给秒删的软件投钱，网易曾经不错，QQ是秒删，他们不缺钱。如果有人做出linux下的千千静听，如果认可你的人多，也还是有收入的。我不是投资者，自然不会投钱。但作为用户，可以给予小额支持。

贡献代码。我会的话，我选择为Audacious写插件，但我不会写代码。因为Audacious可不是我秒删的软件。
————————————————————————————
一切向钱看，开源环境，国外确实比国内好些。但国内赚的是人民币，都不容易。我也没什么可说的。他们可以用爱发电，国内难。

皮肤，皮肤。千千静听和foobar2000都有很多皮肤，都有滚动歌词。本地歌词可控。所以他们是“神”。其他不要说了，未来是版权时代。

**Comment by mikelxk** [comment]
listen1是有本地lrc的 https://github.com/listen1/listen1_desktop/releases/tag/v2.21.6
