### ISSUE TITLE
Failed to exec dist script

### ISSUE THREAD

**Issue by TheOneHliu** [listen1/listen1_desktop#11]
info lifecycle Listen1@1.2.0~dist: Failed to exec dist script
14 verbose stack Error: Listen1@1.2.0 dist: `build --platform win32 --platform darwin --platform linux --arch all`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Listen1@1.2.0
16 verbose cwd E:\WorkSpace\code\listen_1\listen1_desktop
17 error Windows_NT 6.1.7601
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error Listen1@1.2.0 dist: `build --platform win32 --platform darwin --platform linux --arch all`
22 error Exit status 1
23 error Failed at the Listen1@1.2.0 dist script 'build --platform win32 --platform darwin --platform linux --arch all'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Listen1 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     build --platform win32 --platform darwin --platform linux --arch all
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Listen1
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Listen1
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by listen1** [comment]
old build script is broken. please update to recent version and try.
