### ISSUE TITLE
v2.28.0，今天突然发现歌曲搜索没有酷我的音源了，应该是搜索接口被屏蔽了，希望看下

### ISSUE THREAD

**Issue by alferd0806** [listen1/listen1_desktop#1160]

**Comment by scientificworld** [comment]
简单看了一下，酷我那边升级了搜索 API，现在需要在请求时包含 `Hm_token` Cookie 和 `Cross` 标头。`Hm_token` 可以和以前一样从 `Set-Cookie` 响应标头中获取，`Cross` 我暂时还没看出是怎么获得的，相关代码应该在[这个文件](https://h5static.kuwo.cn/www/kw-www/app.41f83dd.js)中。

**Comment by listen1** [comment]
fixed in https://github.com/listen1/listen1_chrome_extension/commit/85cd58f9632a70d317a9202eb52b8e048c0f5d18
