### ISSUE TITLE
所有平台均不能播放

### ISSUE THREAD

**Issue by JRY-Zheng** [listen1/listen1_desktop#126]
win10全新安装，网易云歌单不显示，搜索正常，多个平台图片下载中断后不显示（能看到加载了一半）。全平台点击歌曲后能添加歌单，但是不能播放，推动进度条时间也不变。
另外在 git submodule update --init --recursive时报故（全新安装git win64）：
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by DreamXiao** [comment]
已经无法使用了。。GG

**Comment by JRY-Zheng** [comment]
太惨了，看来还是要自己来才行

**Comment by listen1** [comment]
请更新到新版，确定未使用海外IP访问。
git的问题可能与本机器ssh 秘钥设置有关，请确认 `ssh git@github.com` 可以正确执行
