### ISSUE TITLE
missing script: dist:mac

### ISSUE THREAD

**Issue by bashenandi** [listen1/listen1_desktop#13]
尝试打包 mac 安装包时，提示：
npm ERR! missing script: dist:mac

似乎还没有 mac 安装脚本。

**Comment by listen1** [comment]
已经修改了，谢谢

**Comment by jauzzz** [comment]
@listen1 虾米的封面地址一直不对，可以放进修复计划吗，强迫症很难受。thanks

**Comment by listen1** [comment]
@jauzzz 已经修复
