### ISSUE TITLE
支持全局快捷键

### ISSUE THREAD

**Issue by linghutiantian** [listen1/listen1_desktop#14]
我发现另外一个播放google play music的音乐播放软件，也是electron平台，支持全局快捷键，可以把这个移植过来么？
链接如下：https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/a459ec5ab6e69fae6bf643539657ac369beeb394/src/main/features/core/keyboardShortcuts.js

**Comment by listen1** [comment]
#20 中已经实现，等待merge中

**Comment by listen1** [comment]
感谢反馈，在最新版本中已经增加了全局快捷键支持
