### ISSUE TITLE
关于qq音乐的外链版权问题

### ISSUE THREAD

**Issue by 1147079942** [listen1/listen1_desktop#141]
我国《著作权法》限定，著作权包括信息网络传播权，即以有线或者无线方式向公众提供作品，使公众能够在其个人选定的时间和地点得到作品的权利。根据该条的限定，著作权人对自己的网络作品拥有使用权。该法限定了“使用他人作品，**应当支付报酬**而未支付的”是侵权做法。《最高人民法院关于审理牵涉计量机网络著作权纷争案件适用法律若干问题的解释》第三条限定，已在报刊上刊登或者网络上传播的作品，除著作权人表明或者报刊、期刊社、网络服务提供者受著作权人委托**表明不得转载、摘编的以外**，在网络进行转载、摘编并按有关限定支付报酬、注明出处的，不构成侵权。但转载、摘编作品超出有关报刊转载作品范围的，应当认定为侵权。

**Comment by 1147079942** [comment]
四、【使用本服务的方式】

     4.1本服务仅为您个人非商业性质的使用，除非您与腾讯另有约定。

     4.2您依本协议条款所取得的权利不可转让。

     4.3您不得使用任何方式（包括但不限于第三方软件、插件、外挂、系统、设备等）对本服务进行干扰、破坏、修改或施加其他影响。

     4.4**您应当通过腾讯提供或认可的方式使用本服务，不得通过任何第三方软件、插件、外挂、系统、设备等登录或使用本服务。**

     4.5任何人未经腾讯授权不得使用任何第三方软件、插件、外挂、系统等查看、获取本服务中所包含的腾讯、腾讯合作伙伴或用户的任何相关信息、数据等内容，同时，应当严格遵守腾讯发布的Robots协议等相关协议规则。

建议放弃qq音乐

**Comment by listen1** [comment]
非常感谢您的建议。
考虑到Listen1项目本身为国际开源项目，并不托管在中国境内主机，是否适用于中国法律可能有一定的疑虑。
