### ISSUE TITLE
运行打包命令一直失败

### ISSUE THREAD

**Issue by Abnerzj** [listen1/listen1_desktop#142]
`Fantasy-iMac:listen1_desktop fantasy$ npm run dist:mac

> Listen1@2.4.0 dist:mac /Users/fantasy/Desktop/GitHub/GitHub/listen1_desktop
> CSC_IDENTITY_AUTO_DISCOVERY=false DEBUG=electron-builder electron-builder --platform darwin

/Users/fantasy/Desktop/GitHub/GitHub/listen1_desktop/node_modules/electron-builder/node_modules/yargs/yargs.js:14
const { globalMiddlewareFactory } = require('./lib/middleware')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/fantasy/Desktop/GitHub/GitHub/listen1_desktop/node_modules/electron-builder/node_modules/yargs/index.js:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Darwin 17.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dist:mac"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! Listen1@2.4.0 dist:mac: `CSC_IDENTITY_AUTO_DISCOVERY=false DEBUG=electron-builder electron-builder --platform darwin`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Listen1@2.4.0 dist:mac script 'CSC_IDENTITY_AUTO_DISCOVERY=false DEBUG=electron-builder electron-builder --platform darwin'.
npm ERR! This is most likely a problem with the Listen1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     CSC_IDENTITY_AUTO_DISCOVERY=false DEBUG=electron-builder electron-builder --platform darwin
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Listen1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls Listen1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fantasy/Desktop/GitHub/GitHub/listen1_desktop/npm-debug.log
`

**Comment by listen1** [comment]
看报错信息是不支持es6的语法，请检查node版本，升级到较新版本

**Comment by Abnerzj** [comment]
好的，已经升级最新版本解决，谢谢。
