### ISSUE TITLE
网易云音乐导入歌单只能显示1000首歌曲！

### ISSUE THREAD

**Issue by aoshao** [listen1/listen1_desktop#158]
请问以后能不能增加导入所有歌曲？
辛苦了！

**Comment by zwt-ss** [comment]
这似乎是网易云音乐的限制，我在qq音乐导入网易云歌单也只能导入1000首

**Comment by lizy0327** [comment]
大佬，你是怎么导入1000首歌曲的，我的网易音乐歌单导入成功后只显示6首歌曲。
以下是我的歌单，还请大佬指点
https://music.163.com/#/playlist?id=107708016

**Comment by lizy0327** [comment]
解决此问题的方法：
1.在浏览器（本人使用的chrome83）添加插件版的linten1
2.在插件版listen1里导入网易云音乐的歌单
3.然后通过插件版的listen1的设置备份歌单，歌单会以json的格式下载到本地
4.然后通过客户端导入备份的歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单

**Comment by listen1** [comment]
1000首限制的bug已经在v2.17.0版本中解决，谢谢反馈
