### ISSUE TITLE
windows版本歌单无法加载

### ISSUE THREAD

**Issue by gyje** [listen1/listen1_desktop#16]
windows桌面版点击精选歌单，任选一个歌单点击，一直加载
![1](https://user-images.githubusercontent.com/16876086/32324159-61716456-c005-11e7-9ebe-4a64e3b55c17.gif)

**Comment by listen1** [comment]
因为接口变化问题，网易云音乐和qq音乐的歌单都不能用了，只在chrome插件版中修复了这个问题，一定尽快更新桌面版的安装文件

**Comment by listen1** [comment]
已经更新了桌面版，请下载最新的桌面版listen1
