### ISSUE TITLE
功能建议：搜索歌单

### ISSUE THREAD

**Issue by Ken-Huchi** [listen1/listen1_desktop#161]
不知道是不是我的使用习惯的问题，比如我想找点轻音乐，但是歌单给了很多就不能搜索。网易云搜索之后能分类去搜索歌手还是歌单还是别的，感觉这个功能蛮好的。比如搜索电音，就能用这个关键词找个单，直接打开放就方便很多。

**Comment by listen1** [comment]
你好，v2.17.0版本开始已经支持搜索歌单了（暂时只有网易云，后续会加上其它平台）。谢谢反馈。
