### ISSUE TITLE
播放名字很长的歌曲时按钮与歌名重叠

### ISSUE THREAD

**Issue by TTTPOB** [listen1/listen1_desktop#168]
![image](https://user-images.githubusercontent.com/19909103/64755509-af3a0200-d55d-11e9-9deb-18d651f46ab5.png)
拉宽后正常显示
![image](https://user-images.githubusercontent.com/19909103/64755514-b95c0080-d55d-11e9-8480-20527d95de94.png)
建议把按钮这个元素改成不悬浮的

**Comment by listen1** [comment]
已经在v2.16中修复了，感谢反馈
