### ISSUE TITLE
已经购买的专辑可以听就好了

### ISSUE THREAD

**Issue by cornshek** [listen1/listen1_desktop#171]
具体情况就是，我个人在网易云的账号上购买了一些专辑，如果在这个软件上可以顺利的播放我在网易云上购买的专辑而不是显示“版权问题无法播放”就好了。
播放器很优秀，感谢作者开发！

**Comment by XiaoPika** [comment]
加账号登陆模块背离Listen1开发初衷，不会实现，别想了

**Comment by listen1** [comment]
感谢反馈，主要是工作量的问题，应该会加入未来开发计划中。

Listen1非常支持音乐平台的盈利行为，也支持用户为音乐付费。Listen1的初衷是解决用户的收听体验，并不是为了反抗音乐收费。

**Comment by cornshek** [comment]
> 感谢反馈，主要是工作量的问题，应该会加入未来开发计划中。
> 
> Listen1非常支持音乐平台的盈利行为，也支持用户为音乐付费。Listen1的初衷是解决用户的收听体验，并不是为了反抗音乐收费。

加油！

**Comment by listen1** [comment]
已经实现了登录功能，登录后应该就可以听了
