### ISSUE TITLE
关于全局快捷键

### ISSUE THREAD

**Issue by flousfl** [listen1/listen1_desktop#178]
能否添加一个全局暂停和音量调节

**Comment by bujige** [comment]
同样希望作者能加一个全局暂停和音量调节的快捷键。这两个快捷键感觉太有用了。

**Comment by flousfl** [comment]
> 
> 
> 同样希望作者能加一个全局暂停和音量调节的快捷键。这两个快捷键感觉太有用了。

兄弟，隔壁有暂停
[Listen 1 音乐播放器（Windows 毛玻璃版）](https://github.com/reycn/listen1_desktop_fluent)
> 2.3.1.1 (2019-6-29)
> 添加全局快捷键 Ctrl + Alt + Space 切换 播放/暂停

**Comment by bujige** [comment]
> > 同样希望作者能加一个全局暂停和音量调节的快捷键。这两个快捷键感觉太有用了。
> 
> 兄弟，隔壁有暂停
> [Listen 1 音乐播放器（Windows 毛玻璃版）](https://github.com/reycn/listen1_desktop_fluent)
> 
> > 2.3.1.1 (2019-6-29)
> > 添加全局快捷键 Ctrl + Alt + Space 切换 播放/暂停

谢了。但是我是 Mac 端的，隔壁的用不了。。。

**Comment by flousfl** [comment]
> 
> 
> > > 同样希望作者能加一个全局暂停和音量调节的快捷键。这两个快捷键感觉太有用了。
> > 
> > 
> > 兄弟，隔壁有暂停
> > [Listen 1 音乐播放器（Windows 毛玻璃版）](https://github.com/reycn/listen1_desktop_fluent)
> > > 2.3.1.1 (2019-6-29)
> > > 添加全局快捷键 Ctrl + Alt + Space 切换 播放/暂停
> 
> 谢了。但是我是 Mac 端的，隔壁的用不了。。。

好吧.emmmm
