### ISSUE TITLE
无法导入歌单

### ISSUE THREAD

**Issue by jnabnsn** [listen1/listen1_desktop#183]
无法导入酷狗的歌单。显示“未能打开输入的歌单地址”。附上歌单地址：https://t3.kugou.com/2RX3l28uQV2。     浏览器可以打开。

**Comment by 1813927768** [comment]
咪咕音乐的歌单也不行, http://music.migu.cn/v3/my/playlist/164229925

**Comment by listen1** [comment]
duplicated #111
