### ISSUE TITLE
Windows 64位下无法生成安装包

### ISSUE THREAD

**Issue by xuanll** [listen1/listen1_desktop#19]
![image](https://user-images.githubusercontent.com/6114377/34428506-6208e416-ec88-11e7-8d64-902b4537595c.png)

`npm run dist:win64`提示错误

**Comment by eeyk** [comment]
你要先安装他的依赖包，先npm install安装依赖包

**Comment by somezhe** [comment]
怎么装？

**Comment by Martin730913** [comment]
> 你要先安装他的依赖包，先npm install安装依赖包

执行了也无法安装

**Comment by listen1** [comment]
@eeyk 的回答应该是正确的，如果还有问题请查看具体日志信息
