### ISSUE TITLE
建议增加多媒体键的支持

### ISSUE THREAD

**Issue by ghuserac** [listen1/listen1_desktop#198]
键盘上的多媒体键，可以进行系统级别的播放，暂停，停止，快进，后退，调节音量等操作。基本就是以前walkman上的线控功能。

键盘硬件操控可以不干扰当前全屏主体前提下进行背景音乐的操作。举个典型的例子，在游戏中要切歌，一般要alt+tab切换到桌面，再鼠标点下一首图标。而用键盘多媒体键控制的话不用打断当前游戏进程，按键盘按键即可。

下面链接中右上角一排银白色按键既是多媒体键。
https://item.jd.com/2234339.html

根据我自己的使用经验确定  mpc-hc  和   网易云音乐是支持键盘多媒体键的
由于listen1的独有跨平台优越性，我想从网易云转移到l1上，如能支持不胜感激。

**Comment by zerofancy** [comment]
的确缺少对系统多媒体控制的支持。如果有了对系统多媒体控制的支持，那么我就可以用KDE Connect控制电脑播放了。
