### ISSUE TITLE
建议适配键盘多媒体键，或者增加自定义全局快捷键的功能

### ISSUE THREAD

**Issue by ImKujio** [listen1/listen1_desktop#203]
![image](https://user-images.githubusercontent.com/18486297/78452083-d9027400-76bb-11ea-9034-2dec1da573bf.png)
![image](https://user-images.githubusercontent.com/18486297/78452098-e3bd0900-76bb-11ea-9e6b-83add6b319c1.png)
![image](https://user-images.githubusercontent.com/18486297/78452106-ea4b8080-76bb-11ea-86ce-83e0e2475990.png)
![image](https://user-images.githubusercontent.com/18486297/78452112-f33c5200-76bb-11ea-8f3e-8b3611df369b.png)
如上四个多媒体按键，
或者有大佬告知源码里快捷键监听部分代码位置我自行修改编译，不是前端不太懂js

大概看了下代码发现：main.js
![image](https://user-images.githubusercontent.com/18486297/78452598-b9207f80-76be-11ea-91be-c2bebc20b937.png)
是不是改了这个就可以？

**Comment by listen1** [comment]
duplicated #198
