### ISSUE TITLE
灰色歌曲无法跳过

### ISSUE THREAD

**Issue by BackTrackCRoot** [listen1/listen1_desktop#206]
遇到灰色的歌去，或者说无版权歌曲，没有提示然后就卡在那里不播放下一首。
希望遇到灰色歌去可以替换音乐源或者跳过播放下一首。

**Comment by BackTrackCRoot** [comment]
![QQ图片20200504175926](https://user-images.githubusercontent.com/4964761/80955153-53482480-8e31-11ea-9c0b-7f30426993ce.png)

**Comment by LuoLuoDev** [comment]
up

**Comment by listen1** [comment]
请审计到最新版本，解决了该问题
