### ISSUE TITLE
咪咕音乐资源不能播放。

### ISSUE THREAD

**Issue by YcSaber** [listen1/listen1_desktop#209]
咪咕音乐的资源打不开。

**Comment by listen1** [comment]
请升级到2.7.0版本，修复了该问题

**Comment by HellsingMatt** [comment]
咪咕的音质变得好差啊

**Comment by listen1** [comment]
感谢反馈
咪咕默认标准音质确实太差了。已经修改到高清音质。需要升级一下到v2.7.2

**Comment by HellsingMatt** [comment]
> 感谢反馈
> 咪咕默认标准音质确实太差了。已经修改到高清音质。需要升级一下到v2.7.2

瑞斯拜
