### ISSUE TITLE
建议：像创建歌单一样根据链接收藏歌单

### ISSUE THREAD

**Issue by asd-a** [listen1/listen1_desktop#212]
如题

**Comment by asd-a** [comment]
bug:收藏歌单不能同步

**Comment by asd-a** [comment]
无法导入收藏歌单

**Comment by yujiangqaq** [comment]
主界面左侧创建歌单旁有个+号，把歌单贴进去即可

**Comment by asd-a** [comment]
我是想在![image](https://user-images.githubusercontent.com/40518249/81703093-b7f12800-949e-11ea-951f-e3dca59bdcca.png)
里也加一个![image](https://user-images.githubusercontent.com/40518249/81703209-d820e700-949e-11ea-807d-7140676f3bf5.png)
而且![image](https://user-images.githubusercontent.com/40518249/81703093-b7f12800-949e-11ea-951f-e3dca59bdcca.png)无法导出、同步
现版本：2.7.2

**Comment by listen1** [comment]
用创建歌单的加号打开歌单后点击收藏就可以收藏了。备份是支持收藏歌单的
