### ISSUE TITLE
点右上角关闭按钮应用无法关闭

### ISSUE THREAD

**Issue by openSUSE8496** [listen1/listen1_desktop#216]
Linux mx 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
安装的是AMD64版本，点关闭按钮时界面关闭了但歌一直在播放。只能通过pid杀死应用。。

**Comment by listen1** [comment]
你好，关闭按钮只是最小化功能，如果需要退出请右击状态栏按钮，点击退出
