### ISSUE TITLE
请提供AppImage 供GitHub发布下载

### ISSUE THREAD

**Issue by probonopd** [listen1/listen1_desktop#22]
请提供 [AppImage]（https://appimage.org/）供GitHub发布下载。

提供[AppImage]（http://appimage.org/）将具有以下优点：
- 作为AppImage打包的应用程序可以在许多发行版上运行（包括Ubuntu，Fedora，openSUSE，CentOS，elementary OS，Linux Mint等）
- 一个应用程序=一个文件=超级简单的用户：只需下载一个AppImage文件，[使其可执行]（http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80） ，然后运行
- 不需要拆包或安装
- 没有根需要
- 没有系统库改变
- 开箱即用，无需安装运行时
- 可选桌面与`appimaged`集成
- 可选的二进制增量更新，例如，用于连续构建（仅下载二进制比较）使用AppImageUpdate
- 可以选择GPG2-签名你的AppImages（在文件内）
- 适用于Live ISO
- 双启动多个发行版时可以使用相同的AppImages
- 可以列在可用AppImage的 [AppImageHub]（https://appimage.github.io/apps） 中央目录中
- 可以使用'--appimage-extract`参数作为自解压压缩归档文件

**Comment by listen1** [comment]
已经加入了appimage版本，见发布页 [1.5.2](https://github.com/listen1/listen1_desktop/releases/tag/v1.5.2)

**Comment by probonopd** [comment]
请更新至最新版本的[electron-builder](https://github.com/electron-userland/electron-builder)。 谢谢。
