### ISSUE TITLE
网易云导入问题

### ISSUE THREAD

**Issue by SwS200** [listen1/listen1_desktop#220]
每一个歌单最多导入10首歌，是怎么回事

**Comment by lizy0327** [comment]
我的只能导入6首
https://music.163.com/#/playlist?id=107708016

**Comment by lizy0327** [comment]
解决此问题的方法：
1.在浏览器（本人使用的chrome83）添加插件版的linten1
2.在插件版listen1里导入网易云音乐的歌单
3.然后通过插件版的listen1的设置备份歌单，歌单会以json的格式下载到本地
4.然后通过客户端导入备份的歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单

**Comment by lizy0327** [comment]
解决此问题的方法：
1.在浏览器（本人使用的chrome83）添加插件版的linten1
2.在插件版listen1里导入网易云音乐的歌单
3.然后通过插件版的listen1的设置备份歌单，歌单会以json的格式下载到本地
4.然后通过客户端导入备份的歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单

**Comment by listen1** [comment]
已经在最新版V2.9.0中解决了此问题，感谢反馈。
