### ISSUE TITLE
网易云的歌单因非客户端被限制只能导入10首，求修复！

### ISSUE THREAD

**Issue by Freddd13** [listen1/listen1_desktop#222]
导入网易云音乐的歌单发现只有10首，点击链接可以发现网页提示客户端
![image](https://user-images.githubusercontent.com/50367552/83031640-62ed0e80-a067-11ea-98d8-73aba195bfd8.png)

**Comment by 1062978414** [comment]
顶

**Comment by cmmdwl** [comment]
这玩意不太好修，临时方法是换浏览器ua，直到你的网页能够识别到歌单后用插件版导入并备份

**Comment by lizy0327** [comment]
> 这玩意不太好修，临时方法是换浏览器ua，直到你的网页能够识别到歌单后用插件版导入并备份

请问能说具体点吗？我已经获取到歌单的id了，换浏览器后歌单的id还是不变呢，这么做有什么意义吗，还请指点一二。谢谢

**Comment by lizy0327** [comment]
二楼正解，解决此问题的方法
1.在浏览器（本人使用的chrome83）添加插件版的linten1
2.在插件版listen1里导入网易云音乐的歌单
3.然后通过插件版的listen1的设置备份歌单，歌单会以json的格式下载到本地
4.然后通过客户端导入备份的歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单

**Comment by listen1** [comment]
感谢反馈，已经在v2.8.0修复
