### ISSUE TITLE
希望增加播放本地音乐功能

### ISSUE THREAD

**Issue by shaxiu** [listen1/listen1_desktop#224]
1. 希望可以增加 **播放本地音乐** 的功能
2. 希望可以增加 **将本地音乐添加到歌单** 的功能（有些音乐由于版权问题播放不了）
3. 希望可以增加**自定义皮肤** 的功能

**Comment by listen1** [comment]
#174 related

**Comment by listen1** [comment]
本地音乐已经在v2.17.0版本中加入，谢谢你的建议

**Comment by shaxiu** [comment]
十分感谢！愿listen1越来越好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_desktop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月29日(星期四) 凌晨0:20
收件人:&nbsp;"listen1/listen1_desktop"<listen1_desktop@noreply.github.com&gt;;
抄送:&nbsp;"修"<coderxiu@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [listen1/listen1_desktop] 希望增加播放本地音乐功能 (#224)





 
本地音乐已经在v2.17.0版本中加入，谢谢你的建议

**Comment by shaxiu** [comment]
> 本地音乐已经在v2.17.0版本中加入，谢谢你的建议

十分感谢！愿listen1越来越好！
