### ISSUE TITLE
大佬，网易云歌单只显示10首歌。

### ISSUE THREAD

**Issue by MrXFei** [listen1/listen1_desktop#225]
无论是导入网易云歌单，还是直接点击精选歌单里的网易云歌单，都只能显示前面10首歌，这是什么原因呢？

**Comment by venhow** [comment]
同这个问题，还有虾米好像最多是30首

**Comment by reserveword** [comment]
同发现

**Comment by lizy0327** [comment]
我的只能导入6首
https://music.163.com/#/playlist?id=107708016

**Comment by lizy0327** [comment]
解决此问题的方法：
1.在浏览器（本人使用的chrome83）添加插件版的linten1
2.在插件版listen1里导入网易云音乐的歌单
3.然后通过插件版的listen1的设置备份歌单，歌单会以json的格式下载到本地
4.然后通过客户端导入备份的歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单

**Comment by suxxsfe** [comment]
但我这用chrome插件也只能导入前20首，剩下的不行（网易云的网页上也显示不出来）

**Comment by listen1** [comment]
感谢反馈，已经在v2.8.0修复
