### ISSUE TITLE
希望增加程序内的代理设置

### ISSUE THREAD

**Issue by KellsonM** [listen1/listen1_desktop#227]
希望增加程序内独立的代理设置，这样不会收到例如集团网络限制或者海外用户也能畅通访问。谢谢。

**Comment by wozeiliu** [comment]
++++++++++++++++1

**Comment by wozeiliu** [comment]
虽然我想加入开发，但是我只是一个菜java。如果可以的话，能否简单介绍一下增加
代理功能所需的一些知识。

**Comment by listen1** [comment]
https://github.com/listen1/listen1_desktop/commit/edae6830df3c39a149bdd30431835aa86f8d2955 中添加了该功能，V2.21.0中会正式发布
