### ISSUE TITLE
跳转链接应在系统浏览器中打开

### ISSUE THREAD

**Issue by yujiangqaq** [listen1/listen1_desktop#232]
在歌曲的右侧提供了一个链接按钮，作用在插件版中是跳转到歌曲源界面。而在使用Electron打包的桌面版中，则会使用内置浏览器打开，我认为点击该按钮应该在浏览器中打开或将链接复制到剪切板。

目前来看用户需要点击该按钮的原因有二：
需要将歌曲以链接形式分享给朋友
希望能直接获取到原链接方便其到其他的软件中进行下载等操作

在内置浏览器中打开歌曲链接似乎没有什么用处，希望改进

**Comment by listen1** [comment]
感谢反馈，非常好的建议。修改已经整合到v2.12版本中，请更新客户端
