### ISSUE TITLE
建议，在程序里面的自动更新

### ISSUE THREAD

**Issue by cmmdwl** [listen1/listen1_desktop#235]
可以给程序里面添加一个升级通道，能够下载新版本

**Comment by westfly** [comment]
可以考虑用 scoop进行管理软件更新，蛮方便的。

**Comment by cmmdwl** [comment]
我尝试了一下，可以通过github的版本管理来处理
https://api.github.com/repos/listen1/listen1_chrome_extension/releases/latest
json返回的"zipball_url"适合可以直接进行下载 但是好像下载下来的是代码包，不是发布包， "html_url"可以直接导航到下载页，但是感觉不太对
但是我有些问题，我get clone 项目后，在listen1.html，定位到397行了，但是我遇到了放下script 发现脚本无法运行
最后放了个这个，效果不太好，本来想判断后再来的，<很抱歉，技术是现学现卖的，不太懂在页面二次镶嵌脚本QAQ，fork、pr也不会>

`<p> <a open-url="'https://api.github.com/repos/listen1/listen1_chrome_extension/releases/latest'">  {{_DOWNLOAD_NEW_VERSION}} </a> </p>`
在zh_CN.json第78行添加了
`"_DOWNLOAD_NEW_VERSION": "下载新版本",`
最终我没辙了，先放这吧

@listen1

**Comment by cmmdwl** [comment]
对了，作者的桌面版的代码内镶嵌浏览器代码，好像只改浏览器也不太对，可能需要作者重新处理下代码嵌套，
https://api.github.com/repos/listen1/listen1_desktop/releases/latest
可以利用browser_download_url 来获得下载的url，但是还是有坑，我拉取解析时候会解析出来
listen1_2.17.0_win.exe.blockmap
里面是sha1

**Comment by ViCrack** [comment]
用scoop就行了 , 官方仓库已经包含了
