### ISSUE TITLE
npm run start 出错

### ISSUE THREAD

**Issue by qingnanli** [listen1/listen1_desktop#245]
非常感谢您分享listen1desktop代码！我在npm run start遇上了问题。我首先下载了git安装并在win10命令行里git init，然后我在nodejs网站下载了v14版本的exe安装包，接下来我在win10的cmd里cd到代码目录下，执行命令git submodule update --init --recursive，然后执行了npm install，显示如下：

c:\Program Files\listen1_desktop-master>npm install

> core-js@3.6.5 postinstall c:\Program Files\listen1_desktop-master\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> ejs@3.1.3 postinstall c:\Program Files\listen1_desktop-master\node_modules\ejs
> node --harmony ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> electron@8.4.0 postinstall c:\Program Files\listen1_desktop-master\node_modules\electron
> node install.js

停这里了，因此新开一个cmd窗口，cd到代码目录，然后执行npm run start，出现错误：

c:\Program Files\listen1_desktop-master>npm run start

> Listen1@2.10.0 start c:\Program Files\listen1_desktop-master
> electron ./app --enable-logging

c:\Program Files\listen1_desktop-master\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (c:\Program Files\listen1_desktop-master\node_modules\electron\index.js:14:11)
    at Object.<anonymous> (c:\Program Files\listen1_desktop-master\node_modules\electron\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (c:\Program Files\listen1_desktop-master\node_modules\electron\cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Listen1@2.10.0 start: `electron ./app --enable-logging`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Listen1@2.10.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qingqing\AppData\Roaming\npm-cache\_logs\2020-07-15T03_42_27_182Z-debug.log

log文件如下：
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Listen1@2.10.0\~prestart: Listen1@2.10.0
6 info lifecycle Listen1@2.10.0\~start: Listen1@2.10.0
7 verbose lifecycle Listen1@2.10.0\~start: unsafe-perm in lifecycle true
8 verbose lifecycle Listen1@2.10.0\~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;c:\Program Files\listen1_desktop-master\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\texlive\2018\bin\win32;C:\Program Files (x86)\Common Files\Thunder Network\KanKan\Codecs;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\qingqing\Anaconda3;C:\Users\qingqing\Anaconda3\Library\mingw-w64\bin;C:\Users\qingqing\Anaconda3\Library\usr\bin;C:\Users\qingqing\Anaconda3\Library\bin;C:\Users\qingqing\Anaconda3\Scripts;C:\Users\qingqing\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\qingqing\AppData\Local\Programs\Python\Python36\;C:\Users\qingqing\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\bin;;C:\Users\qingqing\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\qingqing\AppData\Roaming\npm
9 verbose lifecycle Listen1@2.10.0\~start: CWD: c:\Program Files\listen1_desktop-master
10 silly lifecycle Listen1@2.10.0\~start: Args: [ '/d /s /c', 'electron ./app --enable-logging' ]
11 silly lifecycle Listen1@2.10.0\~start: Returned: code: 1  signal: null
12 info lifecycle Listen1@2.10.0\~start: Failed to exec start script
13 verbose stack Error: Listen1@2.10.0 start: `electron ./app --enable-logging`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid Listen1@2.10.0
15 verbose cwd c:\Program Files\listen1_desktop-master
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v14.5.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error Listen1@2.10.0 start: `electron ./app --enable-logging`
22 error Exit status 1
23 error Failed at the Listen1@2.10.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

chrome扩展版本可以用，很方便，感谢！桌面版请帮忙看看

**Comment by Constellation39** [comment]
这可能是一个和网络相关的问题，如果只是需要使用桌面版本请前往 https://github.com/listen1/listen1_desktop/releases

**Comment by qingnanli** [comment]
> 这可能是一个和网络相关的问题，如果只是需要使用桌面版本请前往 https://github.com/listen1/listen1_desktop/releases

嗯嗯，好的！

**Comment by i94u** [comment]
印象中是 electron 安裝時導致的問題，當初參考這篇解決的
https://github.com/electron/electron/issues/20739

問題的原因應該是這個 
https://github.com/cnpm/cnpmjs.org/issues/1530

因為公司環境裝不了 release 的檔案，只好自己編譯，給你參考

也謝謝作者開發 listen1 這個好用的軟體
