### ISSUE TITLE
繁體中文語言選擇

### ISSUE THREAD

**Issue by aunight** [listen1/listen1_desktop#251]
如題pak中明明有繁體中文 但設定中無法選擇
還是還沒製作完呢

**Comment by listen1** [comment]
你好，这是因为使用的默认的electron结构自动生成的翻译。繁体中文仍在招募制作中，如果有兴趣，可以在 listen1/chrome_extension这个项目的i18n下进行翻译。谢谢反馈

**Comment by yujiangqaq** [comment]
我已经做了，期待下一次更新吧

**Comment by listen1** [comment]
已经支持繁体中文
