### ISSUE TITLE
2.13.0 问题

### ISSUE THREAD

**Issue by dubin-learner** [listen1/listen1_desktop#268]
最新版本2.13.0问题有点多啊
1.打开播放页后左上角的关闭无法点击
2.无法创建新歌单，命名时确定无法点击

**Comment by listen1** [comment]
第一个问题在v2.16版本中已经解决
第二个问题我们将在今后跟进，感谢反馈

**Comment by dubin-learner** [comment]
赞！第一个问题解决，第二个暂时没有复现。
有个小建议，设置按钮如果能把设置界面回收更好。例如，歌单页下，点击设置出现设置界面；再次点击设置，设置界面消失，页面还停在原来的歌单页下。否则点了设置之后很难返回原来的页面。
