### ISSUE TITLE
咪咕音乐的歌单导入不了

### ISSUE THREAD

**Issue by goodchengwang** [listen1/listen1_desktop#274]
系统：windows10 
版本：最新版本
导入的地址的url是 http://c.migu.cn/006bz9?ifrom=4b3ed1dea07ce1dabe6cc32359082518
但是导入的时候显示 **未能打开输入的地址**
是我导入的歌单的url有误吗？要怎么导入呢？

**Comment by listen1** [comment]
你好，似乎这个地址是一个跳转连接，请访问后将最后出现在地址栏的实际地址进行导入

**Comment by hongzao0316** [comment]
去咪咕网页版登陆后进入自己的歌单，然后复制当前的URL，格式类似这样：https://music.migu.cn/v3/my/playlist/213076576
这样就可以导入到listen1里面了（自己刚刚试了一下，可行）
