### ISSUE TITLE
希望大神可以添加按下空格暂停/播放音乐的功能

### ISSUE THREAD

**Issue by wanwan-neil** [listen1/listen1_desktop#286]

**Comment by cmmdwl** [comment]
桌面版不好搞这个东西把，按下空格很容易和其他软件起冲突，多个按键的快捷键反倒可以，可以参考全局快捷键ctrl+alt+p
例如默认情况下浏览器里的播放器会使用空格来进行暂停，如果你看个视频后面音乐停了会很不爽的
