### ISSUE TITLE
listen1 新UI计划

### ISSUE THREAD

**Issue by iparanoid** [listen1/listen1_desktop#3]
业余时间免费设计
也算是为开源贡献一点力量
感兴趣的可以联系我

**Comment by listen1** [comment]
感谢，能把样稿发给我的邮箱或者在这帖子下面吗？

**Comment by iparanoid** [comment]
业余时间正在设计 还没有完成 完成后用Sketch导出发布吧

**Comment by iparanoid** [comment]
![listen1](https://cloud.githubusercontent.com/assets/6026988/19641524/a76a2218-9a13-11e6-925f-72d010a213d9.png)
最近有点忙 框架初步已成 比较理想化一点
随后会更新进度

**Comment by iparanoid** [comment]
![listen1](https://cloud.githubusercontent.com/assets/6026988/19679888/385d57fa-9ad6-11e6-8b69-bb6b0eda08dc.jpg)

**Comment by iparanoid** [comment]
![default](https://cloud.githubusercontent.com/assets/6026988/19846888/d4815176-9f7d-11e6-91b8-f4ce373fc255.jpg)
![default](https://cloud.githubusercontent.com/assets/6026988/19846889/d4b3419a-9f7d-11e6-95c9-bd5c1bc1f72d.jpg)
![default](https://cloud.githubusercontent.com/assets/6026988/19846891/d4ff1b38-9f7d-11e6-993d-7387a1e2a373.jpg)
![listen1](https://cloud.githubusercontent.com/assets/6026988/19846890/d4ff0300-9f7d-11e6-919f-b2a0195dd604.jpg)
更新中

**Comment by patricorgi** [comment]
@iparanoid 好棒啊！

**Comment by wholegale39** [comment]
请问新ui更新完毕了吗？

**Comment by listen1** [comment]
@iparanoid UI设计非常棒，可是因为技术能力有限还不足以全部实施你的方案，以后会慢慢采纳。

在最近的发布中，歌曲主页页面参考了你的设计，谢谢你对Listen1项目的贡献！

**Comment by iparanoid** [comment]
@listen1 需要sketch源文件的话 留言即可

**Comment by listen1** [comment]
@iparanoid 很需要，可以直接分享在这个issue或者邮件给我，谢谢

**Comment by xianghongai** [comment]
Nice UI!

**Comment by iparanoid** [comment]
@listen1 上的少 刚看到回复.... 源文件已经邮件发送邮箱 希望能够帮到你

**Comment by dingdingrao** [comment]
@iparanoid 能否发一份源文件，我尝试一下这个UI效果~

**Comment by listen1** [comment]
感谢iparanoid, 2.0版开始已经采用了新UI
