### ISSUE TITLE
更新软件后无法播放“创建的歌单”里的歌单

### ISSUE THREAD

**Issue by YuanchenZhu2020** [listen1/listen1_desktop#310]
Platform: Windows 10
Version: 2.17.2

更新 2.17.2 版本后无法播放“创建的歌单”里的歌曲，表现为：能显示歌曲名称、封面，但时间显示为 "00:00"。其余板块都可以正常播放。重启后仍然有前述问题。

**Comment by cjy825** [comment]
我也遇到这个问题了，但是我换成 chrome 插件版本了。你可以先导出到 GitHub lab 安装插件后重新导入。
感觉维护各个平台版本确实挺辛苦的，还是浏览器插件来的方便

**Comment by Sglight** [comment]
Linux 也遇到了同样的问题，回退到 2.17.1 一切正常。

**Comment by listen1** [comment]
非常抱歉在升级版本时忽略了旧版本的兼容性问题。
问题已经确认，在2.17.1版本之前歌单中每首歌的url字段会保存为id值，在新版本中url字段修改为歌曲实际链接。所以解析旧值时会误以为url已经被解析而尝试访问id为地址加载字段。

正在修复过程中，遇到该问题的用户暂时不要删除歌单，等新版本发布后直接安装就可以访问了。

**Comment by listen1** [comment]
已经在v2.17.3版本中修复了该问题。感谢反馈 @YuanchenZhu2020
