### ISSUE TITLE
音乐完全无法播放

### ISSUE THREAD

**Issue by cmmdwl** [listen1/listen1_desktop#312]
2.17.5本版本任何音乐都无法播放,回退2.17.0后播放器正常

**Comment by listen1** [comment]
请问您的网络环境和操作系统是什么？

**Comment by cmmdwl** [comment]
> 请问您的网络环境和操作系统是什么？

w10 2004 移动网

**Comment by cmmdwl** [comment]
最终解决方法,使用系统卸载后再次安装重新导入歌单即可正常
