### ISSUE TITLE
建议升级electron到11，原生支持apple silicon

### ISSUE THREAD

**Issue by AlexStacker** [listen1/listen1_desktop#313]
`electron` 从11开始原生支持`Apple M1`芯片，[参考链接](https://www.electronjs.org/releases/stable?page=2#11.0.0)，希望可以升级 `electron`，提供原生支持的版本。

**Comment by listen1** [comment]
已经升级了electron到v11 https://github.com/listen1/listen1_desktop/commit/cd70e10e8ee5fd97911b538cbcec7cc7cb5b9492

具体怎么打成支持M1芯片的包还需要研究一下
