### ISSUE TITLE
寻找可靠的国内分发渠道方式

### ISSUE THREAD

**Issue by listen1** [listen1/listen1_desktop#321]
国内很多来信反应访问github下载软件存在连接不稳定的问题，现在寻找国内可用的分发源

要求：

* 稳定的速度
* 无需注册下载
* （可选）可支持匿名上传
* （可选）可支持自动同步

如果有好的分发渠道欢迎留言。

现在已知的mac版分发渠道：

https://macwk.com/soft/listen1

**Comment by lynnguo666-personal** [comment]
Coding云 
坚果云（需WebDAV）【推荐】

**Comment by yujiangqaq** [comment]
lanzou云

**Comment by yujiangqaq** [comment]
欸，想不到现在包体已经过100mb了，这样蓝奏云免费版本没法用了，不然尝试下次发布时做个磁力链接？依靠社区的力量做种？

**Comment by listen1** [comment]
100M是包含了32位和64位的包，单独打包应该能降到100M以下。

试了一些云都需要手机注册啊，有没有邮箱注册就能分享的

**Comment by yujiangqaq** [comment]
> 100M是包含了32位和64位的包，单独打包应该能降到100M以下。
> 
> 试了一些云都需要手机注册啊，有没有邮箱注册就能分享的

在国内不存在的，都要手机号实名(¯―¯٥)
其实想了一下，通过这种方式限制用户数量避免做大以后出事也挺好

**Comment by lynnguo666-personal** [comment]
> 100M是包含了32位和64位的包，单独打包应该能降到100M以下。
> 
> 试了一些云都需要手机注册啊，有没有邮箱注册就能分享的
有一个项目是Github下载加速的
这个是链接
eg：HK服务器 WIN版本的下载链接 
https://pd.zwc365.com/seturl/https://github.com/listen1/listen1_desktop/releases/download/v2.17.9/listen1_2.17.9_win.exe

**Comment by listen1** [comment]
感谢@yujiangqaq 提供的蓝奏云国内镜像地址
https://github.com/listen1/listen1_desktop/issues/350

**Comment by Geeyun-JY3** [comment]
> 100M是包含了32位和64位的包，单独打包应该能降到100M以下。

原来是这样，怪不得 2.17.8 到 2.17.9 包大小翻了个倍

**Comment by cmmdwl** [comment]
https://github.com/zwc456baby/file-proxy

示例：
# 原来的下载方式是:
wget https://github.com/listen1/listen1_desktop/releases/download/v2.18.0/listen1_2.18.0_win_x64.7z
# 使用 CloudFlare 代下功能
wget https://pd.zwc365.com/cfdownload/https://github.com/listen1/listen1_desktop/releases/download/v2.18.0/listen1_2.18.0_win_x64.7z
# 使用本站服务器代下功能
wget https://pd.zwc365.com/seturl/https://github.com/listen1/listen1_desktop/releases/download/v2.18.0/listen1_2.18.0_win_x64.7z

这个操作有些油猴脚本可以实现
