### ISSUE TITLE
可否发行Win 32x 的安装包呢

### ISSUE THREAD

**Issue by Jack6811** [listen1/listen1_desktop#327]
可否发行Win x32的安装包呢？目前好像由于项目设置的原因32x和64x的安装包是同名文件，且会先生成32x后64x导致32x被复写。
目前我自己由于两台电脑有一个32x所以我自己构建安装包，如果这样会增加发行难度且不普及的话就算了，还是我自己clone构建吧。

对了，可不可以实现倍速播放音乐？

**Comment by listen1** [comment]
修改electron-builder读取的packge.json相关配置后，现在支持了windows 32位安装包
https://github.com/electron-userland/electron-builder/issues/1897

请从主页或release页面下载v2.17.9以后的版本，选择win ia32结尾的安装包

感谢你的反馈
