### ISSUE TITLE
更新到最新版后打开空白

### ISSUE THREAD

**Issue by zsguy** [listen1/listen1_desktop#334]
上周到看推广文章安装的,一直正常使用.结果前天自动更新了最新版,打开就是一个白色窗口,还以为自己电脑出问题,卸载在github再下载安装打开,还是白色一个窗口,请问这个怎么解决?
#

**Comment by listen1** [comment]
感谢反馈。请问出问题的版本和你的操作系统的版本是什么？

**Comment by zsguy** [comment]
Desktop v2.17.9  
系统wixn10 x64 2004 19041.685  
上一版本是正常运行,自动更新/重新安装最新版打开,一个白色的窗口
> 感谢反馈。请问出问题的版本和你的操作系统的版本是什么？

**Comment by zsguy** [comment]
安装回上一个版本v2.17.8,能正常用,然而关闭就会自动更新成2.17.9,打开空白,设置找过没有不自动更新的选项,无奈

**Comment by listen1** [comment]
推荐在官方发布页面下载之前版本, Listen1本身不支持自动更新，所以应该不会强制升级

https://github.com/listen1/listen1_desktop/releases

打开空白可能是开始时js加载出现了错误，我们会尝试在windows 10环境中复现一下。

**Comment by zsguy** [comment]
(苦笑),能让我用着旧版本不自动更新我就不会忍不住上来说了,他真的自动更新,还在上面那目录留下安装包不删除,好吧你关闭吧,我过一段时间等你们更新一两个版本再用好了

**Comment by listen1** [comment]
如果方便能不能把安装包发给我看一下，这种情况之前这边打包没遇到过。谢谢。邮件地址是  githublisten1@gmail.com

**Comment by zsguy** [comment]
发过去了,突然才发现这v2.17.8才53M,v2.17.9一下涨到103M

**Comment by listen1** [comment]
好的，感谢。v2.17.9 由于加入了32位系统安装支持所以打包体积较大。
