### ISSUE TITLE
关于自动更新的问题

### ISSUE THREAD

**Issue by 78740300** [listen1/listen1_desktop#337]
请问windows客户端版本在哪里进行自动更新呢？想更新到最新版本没有提示

**Comment by listen1** [comment]
现在还没有集成自动更新的功能，可以访问 listen1.github.io/listen1 网页下载最新版本

自动更新功能已经在计划中，谢谢你的反馈

**Comment by 78740300** [comment]
感谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_desktop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月10日(星期天) 晚上9:58
收件人:&nbsp;"listen1/listen1_desktop"<listen1_desktop@noreply.github.com&gt;;
抄送:&nbsp;"我大步向前　　～"<78740300@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [listen1/listen1_desktop] 关于自动更新的问题 (#337)





 
现在还没有集成自动更新的功能，可以访问 listen1.github.io/listen1 网页下载最新版本
 
自动更新功能已经在计划中，谢谢你的反馈

**Comment by 78740300** [comment]
windows更新到2.17.8之后，创建的歌单歌曲不能听了，这可能是什么原因造成的呢？

**Comment by listen1** [comment]
歌单是通过什么方式创建的？可能需要更详细的信息方便定位问题
