### ISSUE TITLE
国内蓝奏云加速下载

### ISSUE THREAD

**Issue by yujiangqaq** [listen1/listen1_desktop#350]
个人维护的Releases镜像，只保留50mib以上的大文件，长期维护，人工爬虫，争取在更新的第一时间就上传
https://yujiangqaq.lanzoux.com/b0104q61e
密码:listen1

**Comment by listen1** [comment]
非常感谢，太及时了。稍后更新到readme和项目主页去

**Comment by listen1** [comment]
能否加一个安卓版的下载，有用户问到，谢谢

**Comment by yujiangqaq** [comment]
> 能否加一个安卓版的下载，有用户问到，谢谢

https://yujiangqaq.lanzous.com/b0104q89e
密码:listen1
这个是安卓的，两个分开比较好找

**Comment by yujiangqaq** [comment]
来晚了，2.18.0 蓝奏云已更新

**Comment by yujiangqaq** [comment]
抱歉地通知一个消息，因为一些特殊的个人原因，在2021年12月1日0点后将会停止维护并从蓝奏云上移除Releases镜像，在此之前会一直保持更新

**Comment by listen1** [comment]
好的，谢谢一直以来及时的更新。

**Comment by macwkcom** [comment]
> 好的，谢谢一直以来及时的更新。

开发者好，我是 macwk 的站长，最近几个版本时有 arm64 的包，时无是什么原因呀。

**Comment by listen1** [comment]
> > 好的，谢谢一直以来及时的更新。
> 
> 开发者好，辛苦了！我是 macwk 的站长，最近几个版本时有 arm64 的包，时无是什么原因呀。

你好。测试arm64包打开时会提示已损坏，所以没有放上去。用universal的包就没问题。

**Comment by macwkcom** [comment]
> > > 好的，谢谢一直以来及时的更新。
> > 
> > 
> > 开发者好，辛苦了！我是 macwk 的站长，最近几个版本时有 arm64 的包，时无是什么原因呀。
> 
> 你好。测试arm64包打开时会提示已损坏，所以没有放上去。用universal的包就没问题。

OK，网站目前已重写安装器，对于这些开源软件以及不需要权限的软件安装不再需要密码了。

在安装的过程中会检测电脑是否开启了任何来源，未开启则帮其开启，另外会检查应用的签名状态，如果未签名则会帮用户绕过签名，像 Listen 1 未签名在打包的时候我会对其进行 Adhoc 的签名，防止无法运行。


![image](https://user-images.githubusercontent.com/53843550/119338003-0811e580-bcc2-11eb-90a5-69c317563dd4.png)
![image](https://user-images.githubusercontent.com/53843550/119338054-1b24b580-bcc2-11eb-9e90-9c82ec26dd4f.png)
![image](https://user-images.githubusercontent.com/53843550/119338157-3bed0b00-bcc2-11eb-8312-38fd4a2ab3f5.png)

**Comment by zuanhunzi** [comment]
大佬，我怎么打不开链接的网页？

**Comment by Geeyun-JY3** [comment]
> 大佬，我怎么打不开链接的网页？

蓝奏的问题：https://www.ruancan.com/wangluo/519447.html
> 把链接中的 lanzous 替换成 lanzoux

**Comment by macwkcom** [comment]
> 大佬，我怎么打不开链接的网页？

![image](https://user-images.githubusercontent.com/53843550/126072742-7104d262-5f87-4bef-9b03-7f41a65d6fbe.png)

你应该说的是网站打不开不是没法下载吧？

**Comment by yujiangqaq** [comment]
> 大佬，我怎么打不开链接的网页？

lanzou的问题，链接已更新。
请注意，我的国内分流到年底就会停止，因为我没有更多的精力去维护它。请及时寻找替代品，或确保拥有稳定的国际连接线路。
最好不要依赖任何分流，你永远不知道分流者会不会夹带私货（虽然我不会）

**Comment by ViCrack** [comment]
这个也可以用gitee直接自动镜像同步github的吧 , 也不需要人工上传到lanzou了

**Comment by yujiangqaq** [comment]
> 这个也可以用gitee直接自动镜像同步github的吧 , 也不需要人工上传到lanzou了

是的，但是有人不喜欢gitee。lanzou分流已经不维护了。
