### ISSUE TITLE
咪咕音乐的精选歌单打开页面 404

### ISSUE THREAD

**Issue by Geeyun-JY3** [listen1/listen1_desktop#351]
点击咪咕音乐精选歌单的 <kbd>🔗链接</kbd> 按钮后打开的歌单页都是 `https://music.migu.cn/v3/music/playlist/mgplaylist`

**Comment by listen1** [comment]
感谢反馈，已经在如下commit中修复
https://github.com/listen1/listen1_chrome_extension/commit/40d99b4248520161fc43f022ae8243f62851d89f
