### ISSUE TITLE
Github 授权问题

### ISSUE THREAD

**Issue by NoDocCat** [listen1/listen1_desktop#359]
初次安装打开, 完成授权后网络请求已返回 access_token, 如图: 
![image](https://user-images.githubusercontent.com/20502666/106750389-be45b680-6662-11eb-9832-4a1ca01b1ca1.png)
![image](https://user-images.githubusercontent.com/20502666/106750466-d9b0c180-6662-11eb-9a97-6aa8daf9ae5f.png)

但是写入到 Local Storage 的值是 undefined(此处原因未知, 我没办法打开授权窗口的调试工具):
![image](https://user-images.githubusercontent.com/20502666/106750614-049b1580-6663-11eb-9ae7-b3188776ee74.png)

进而导致这里出现异常, 无法进行后续流程:
![image](https://user-images.githubusercontent.com/20502666/106750744-314f2d00-6663-11eb-814c-dd7507810685.png)

希望尽早修复

**Comment by NoDocCat** [comment]
进一步追踪：发现 https://github.com/login/oauth/access_token 接口返回的不是 JSON, 而是文本和 network 中显示的一致.
我去翻了一下 API 文档, 并没有相关说明. 已经给 Github 反馈了, 等待确认后再说吧.

**Comment by NoDocCat** [comment]
@listen1 
问题确认, request headers 中的 accept 必须设置成 `application/json`. 才能保证返回的也是 json.
如果按照当前版本的设置, 值为 `application/json, text/plain, */*` 可能会导致返回值被降级到 text. (同样原因未知, 官方还未回复)
现在有两个方式去解决, 
一个是修改 axios 配置, 把 accept 强制改成 `application/json`.
另一个是检查返回的 content-type, 当返回的 content-type 是 `application/x-www-form-urlencoded; charset=utf-8` 时, 降级到文本解析.
确定用那种方式的话, 麻烦告知一声, 我来混个 pr. 😊

临时解决方法: F12 打开控制台并执行:
```js
axios.defaults.headers.common.Accept = "application/json"
```

附图:
![image](https://user-images.githubusercontent.com/20502666/106757701-a6266500-666b-11eb-8719-ef8ddfbb9abe.png)

![image](https://user-images.githubusercontent.com/20502666/106757751-b3dbea80-666b-11eb-8e68-63903ebe7e59.png)

**Comment by listen1** [comment]
感谢非常详细的问题解决过程。我认为可以强制把accept设置为json类型。期待PR
