### ISSUE TITLE
Linux端桌面歌词显示问题

### ISSUE THREAD

**Issue by FZDSLR** [listen1/listen1_desktop#362]
- Listen 1 版本： 2.18.0
- Linux发行版及桌面环境： Manjaro + Xfce
- 问题： 桌面歌词重叠显示
![截图_2021-02-08_03-35-02](https://user-images.githubusercontent.com/62922415/107145492-d9733780-697c-11eb-80a7-b5e1afb36f8c.png)

**Comment by Borber** [comment]
arch + kde 2.18.0 也出现了同样的问题
