### ISSUE TITLE
开启Listen1时调整音量时会有曲目的框，遮挡视野，如何关闭

### ISSUE THREAD

**Issue by DamonCZH** [listen1/listen1_desktop#370]
如题

**Comment by listen1** [comment]
你好，谢谢反馈。不太明白你的意思，方便的话能否有个截图说明

**Comment by DamonCZH** [comment]
好，Github的issue里没找到贴图的地方。
问题如上所示，如果不开启Listen1的话，调整音量只会出现左边的音量条，开启了之后再调整音量红框当中的内容出现，比较遮挡视野。
By the way，chrome浏览器在播放视频或者音乐的时候也是这种情况，但是它可以通过&nbsp;chrome://flags/#hardware-media-key-handling 来关闭，希望这一点对解决问题有帮助。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Listen 1"<notifications@github.com&gt;; 
发送时间: 2021年2月13日(星期六) 晚上7:56
收件人: "listen1/listen1_desktop"<listen1_desktop@noreply.github.com&gt;; 
抄送: "常子浩"<2535180928@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [listen1/listen1_desktop] 开启Listen1时调整音量时会有曲目的框，遮挡视野，如何关闭 (#370)





 
你好，谢谢反馈。不太明白你的意思，方便的话能否有个截图说明

**Comment by mikelxk** [comment]
![image](https://user-images.githubusercontent.com/32220948/107859008-e5299700-6e71-11eb-9fc5-3ff559863988.png)

@DamonCZH 指的应该是windows会自动使用chrome的mediaSession生成这种音量框，如果要加个选项的话electron下应该这样实现https://github.com/electron/electron/issues/18253#issuecomment-589542934
然而这样做的话也会取消mediaSession的其他功能，如使用媒体键来控制listen1.

**Comment by DamonCZH** [comment]
那这样的话，我还有个问题，就是我想用这个框框里的按键切换上一首歌或者下一首，不过目前只有暂停键可以用，这个问题应该如何解决呢？

**Comment by mikelxk** [comment]
之前是有切歌有这个功能的，然后这玩意和自动换源有点冲突就暂时删掉了，应该等几个版本就有这个功能了 🏃

**Comment by listen1** [comment]
> 之前是有切歌有这个功能的，然后这玩意和自动换源有点冲突就暂时删掉了，应该等几个版本就有这个功能了 🏃

还有一个原因是mediaSession的切歌在后台进行，那后台需要有获取歌曲播放地址的功能，而这部分代码暂时还在前台实现的。后期可能等待Dumeng的PR把获取媒体资源的相关功能打包成一个单独的库。这样后台就可以支持切歌功能了。

**Comment by mikelxk** [comment]
已实现了mediaSession上/下一首
