### ISSUE TITLE
Linux 高分屏下托盘图标模糊

### ISSUE THREAD

**Issue by glatavento** [listen1/listen1_desktop#375]
如图

![image](https://user-images.githubusercontent.com/76601050/108153718-aff1a300-7116-11eb-807f-947c379892ea.png)

![image](https://user-images.githubusercontent.com/76601050/108153663-905a7a80-7116-11eb-9ced-e33c0bff7916.png)

```
系统信息
OS: Manjaro 20.2.1 Nibia
Kernel: x86_64 Linux 5.4.95-1-MANJARO
Resolution: 3000x2000
DE: KDE 5.78.0 / Plasma 5.20.5
```

**Comment by glatavento** [comment]
经测试，Windows 下也模糊
![image](https://user-images.githubusercontent.com/76601050/108165465-914ad680-712d-11eb-8ef1-ae87bd9ff0f1.png)

**Comment by mikelxk** [comment]
#382
