### ISSUE TITLE
无法导入QQ音乐歌单

### ISSUE THREAD

**Issue by XingHuo452** [listen1/listen1_desktop#381]
QQ音乐歌单无法导入
![(_2LE`~{9($QA7YE@_@1Z F](https://user-images.githubusercontent.com/79151855/108587391-39f77100-738e-11eb-833b-6dc5a374abf6.png)

**Comment by listen1** [comment]
能否把歌单地址留一下，或者发邮件给我，谢谢

**Comment by XingHuo452** [comment]
好的，https://c.y.qq.com/base/fcgi-bin/u?__=EWUruJF


| |
养猪
|
|
gjcaini@126.com
|
签名由网易邮箱大师定制
在2021年2月20日 15:18，Listen 1<notifications@github.com> 写道：

能否把歌单地址留一下，或者发邮件给我，谢谢

**Comment by listen1** [comment]
由于现在识别歌单的机制还是找的url中的歌单id，所以暂时还处理不了这种短链接的格式。

暂时可以打开短链接后把重定向的url复制后在listen1中打开。

后期我们会加上对短链接歌单地址的解析。谢谢。

**Comment by XingHuo452** [comment]
| |
养猪
|
|
gjcaini@126.com
|
好的，谢谢你
签名由网易邮箱大师定制
在2021年2月20日 15:25，Listen 1<notifications@github.com> 写道：

由于现在识别歌单的机制还是找的url中的歌单id，所以暂时还处理不了这种短链接的格式。

暂时可以打开短链接后把重定向的url复制后在listen1中打开。

后期我们会加上对短链接歌单地址的解析。谢谢。

**Comment by listen1** [comment]
在V2.21版本中加入了对QQ短链接歌单的支持 https://github.com/listen1/listen1_chrome_extension/commit/baf3c89c2b47a58f0ca0e6af10b7c45ce3218e2c

**Comment by maojunan1205** [comment]
https://c.y.qq.com/base/fcgi-bin/u?__=QlgPnGzlO1Nn这个QQ音乐的始终导不进去啊

**Comment by maojunan1205** [comment]
这个qq的跟歌单一直导不进去https://c.y.qq.com/base/fcgi-bin/u?__=QlgPnGzlO1Nn

**Comment by maojunan1205** [comment]
@listen1

**Comment by CN-LPani** [comment]
我也是导不进去
