### ISSUE TITLE
无法添加本地歌曲

### ISSUE THREAD

**Issue by wszswppx** [listen1/listen1_desktop#383]
在本地音乐中点击“添加歌曲”，选择后无事发生，本地音乐歌单仍然是空白。

**Comment by mikelxk** [comment]
能给下console的log嘛？

**Comment by QN-time** [comment]
对我也无法添加歌曲 音乐格式是普通的mp3格式 还有一部分是无损的flac格式

**Comment by QN-time** [comment]
我的是windows x64的桌面版本

**Comment by mikelxk** [comment]
能用f12开一下console的log嘛？

**Comment by QN-time** [comment]
Uncaught (in promise) TypeError: tracks.forEach is not a function
    at Object.lm_add_playlist [as add_playlist] (localmusic.js:109)
    at Object.post (loweb.js:184)
    at app.js:846
DevTools failed to load SourceMap: Could not parse content for file:///E:/LISTEN12/resources/app.asar/listen1_chrome_extension/js/vendor/angular.min.js.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///E:/LISTEN12/resources/app.asar/listen1_chrome_extension/js/vendor/axios.min.map: Unexpected end of JSON input
DevTools failed to load SourceMap: Could not parse content for file:///E:/LISTEN12/resources/app.asar/listen1_chrome_extension/js/vendor/async.min.map: Unexpected end of JSON input

**Comment by mikelxk** [comment]
嗯。。。之前的确看到过这个bug，请问版本是最新的吗？

**Comment by QN-time** [comment]
当前版本为2.18.0

**Comment by QN-time** [comment]
应该是最新的吧= =，我没记错吧

**Comment by mikelxk** [comment]
> 应该是最新的吧= =，我没记错吧

是的..好像是track的格式有问题，似乎和 https://github.com/listen1/listen1_chrome_extension/pull/468 有关？

**Comment by QN-time** [comment]
非常抱歉我只有大一，还不能看懂这些代码。没办法给你在这方面提供帮助。

**Comment by mikelxk** [comment]
https://github.com/mikelxk/listen1_desktop/releases/tag/v2.18.1-canary

**Comment by QN-time** [comment]
请问能发一下百度云或者蓝奏云的版本吗= =，没有外网下不了TAT

**Comment by mikelxk** [comment]
Try https://ghproxy.com/

**Comment by reber0** [comment]
https://github.com/listen1/listen1_desktop/issues/365 同样问题

**Comment by Su-Ziqing** [comment]
同问

**Comment by reber0** [comment]
@Su-Ziqing 最新版没问题
