### ISSUE TITLE
github登录之后点击已完成没反应

### ISSUE THREAD

**Issue by rumosky** [listen1/listen1_desktop#388]
如题，在我登录github账户之后，已经显示已完成授权。但是原页面的已完成授权那个按钮点击没反应。只能点击旁边的遇到问题，重新打开页面。然后重新打开页面之后显示的是已经完成了授权，请返回原页面点击已完成授权。如此循环往复，很无语

**Comment by mikelxk** [comment]
新的2.19版本已经解决了这个问题
