### ISSUE TITLE
QQ音乐再次不能播放了

### ISSUE THREAD

**Issue by jackyting825** [listen1/listen1_desktop#39]
刚刚发现QQ音乐源的音乐不能播放了.昨天都是正常的.估计尿性的腾讯又做了啥屏蔽了....

**Comment by 13076267131** [comment]
我也是

**Comment by xushuduo** [comment]
/Applications/Listen1.app/Contents/Resources/app/listen1_chrome_extension/js/provider

qq.js （引用：https://github.com/listen1/listen1_chrome_extension/issues/147）
把 http://dl.stream.qqmusic.qq.com/C200 改成 http://ws.stream.qqmusic.qq.com/C100

xiami.js （引用：https://github.com/listen1/listen1_chrome_extension/issues/140）
第一处：xm_bootstrap_track下
MP3源地址：sound.url = 'http:'+caesar(location);
歌曲所在专辑图片：track.img_url = 'http:'+data.data.trackList[0].pic;
歌词：track.lyric_url = 'http:'+data.data.trackList[0].lyric_url;
第二处：xm_show_playlist下
歌单封面图：default_playlist.cover_img_url = $(this).find('img')[0].src.replace('chrome-extension', "http");

**Comment by jackyting825** [comment]
1.6.1版本已经可以播放
