### ISSUE TITLE
点击指定歌曲播放其他歌曲问题

### ISSUE THREAD

**Issue by haoming1100** [listen1/listen1_desktop#403]
![image](https://user-images.githubusercontent.com/29730704/110202607-da788580-7ea4-11eb-897e-384ce315059f.png)
如图，我在点击播放全部的时候的，会跳过**海阔天空**，直接播放**认真**，但是此时我点击**海阔天空**就会随机播放其他歌曲，

**Comment by listen1** [comment]
请检查一下代理设置，或检查一下接入网络所在国家和地区，某些地区的访问可能受到限制。

如果仍有问题，麻烦留一下歌单的平台和相关地址，方便定位问题。谢谢
