### ISSUE TITLE
桌面歌词问题

### ISSUE THREAD

**Issue by GoCross** [listen1/listen1_desktop#406]
版本：V2.19.0
系统版本：Ubuntu 20.04
调整透明度的功能只修改了按钮的透明度，未修改背景的透明度。
![4W_ 9F1HST_9X%FPR(HU}GO](https://user-images.githubusercontent.com/40139388/110727897-0a35dd80-8257-11eb-93ef-60d8bf6166a3.png)
![8_R`~YMTK{$~FR2WQMZ12UG](https://user-images.githubusercontent.com/40139388/110727907-0e61fb00-8257-11eb-9468-ff7b8b06acaa.png)
另外点了锁定歌词之后，无法解锁。

**Comment by listen1** [comment]
https://github.com/listen1/listen1_desktop/pull/411
