### ISSUE TITLE
不会安装，，，

### ISSUE THREAD

**Issue by gaotingqi** [listen1/listen1_desktop#41]
新人一枚，不知道这个怎么安装，求大佬指导

**Comment by qinkangdeid** [comment]
你的是什么平台就下载什么平台的安装包就安装啊

**Comment by JAYRANRAIN** [comment]
建议可以打包一个deb或者APPimage包,方便使用

**Comment by listen1** [comment]
感谢反馈，最新版本2.0都是下载点击就能安装了。Linux也是通过AppImage支持一键安装
