### ISSUE TITLE
[Bug] Unusual behavior of the Listen1 player after deleting songs from the playlist

### ISSUE THREAD

**Issue by 01xz** [listen1/listen1_desktop#425]
OS: Windows10 20H2

![1](https://user-images.githubusercontent.com/73350430/112628024-53984680-8e6d-11eb-822f-c77f262854b0.png)
![2](https://user-images.githubusercontent.com/73350430/112628034-572bcd80-8e6d-11eb-9bee-a9ff78a00370.png)
![3](https://user-images.githubusercontent.com/73350430/112629398-3e241c00-8e6f-11eb-9631-9dff4fa5098d.png)

**Comment by listen1** [comment]
fixed in V2.20
