### ISSUE TITLE
i18n break on listen1 desktop

### ISSUE THREAD

**Issue by mikelxk** [listen1/listen1_desktop#427]
![image](https://user-images.githubusercontent.com/32220948/113280922-85028d80-9317-11eb-9682-92bfbe3f441d.png)
Using the new commit from upstream, showing
` Failed to load resource: net::ERR_FILE_NOT_FOUND  /C:/i18n/zh-CN.json:1`

**Comment by listen1** [comment]
resolved in https://github.com/listen1/listen1_chrome_extension/commit/5a9d2a41087540f4c1b4c58eaa8fddd653c15698

**Comment by mikelxk** [comment]
Thanks for the quick fix
