### ISSUE TITLE
咪咕的好像都不能听了

### ISSUE THREAD

**Issue by hastings2k** [listen1/listen1_desktop#428]
大概从一周前开始，咪咕的音乐就都不能听了。是不是因为需要登录了？
win桌面版

**Comment by listen1** [comment]
似乎是咪咕要求登录，否则音乐文件获取不到了。已经在最近的版本中增加了登录的相关功能，应该会尽快加入咪咕的登录。

**Comment by hastings2k** [comment]
感谢解答，大佬辛苦。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Listen ***@***.***>
发送时间: 2021年4月2日 11:14
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [listen1/listen1_desktop] 咪咕的好像都不能听了 (#428)


似乎是咪咕要求登录，否则音乐文件获取不到了。已经在最近的版本中增加了登录的相关功能，应该会尽快加入咪咕的登录。

―
