### ISSUE TITLE
希望尽快原生支持apple silicon芯片设备

### ISSUE THREAD

**Issue by cheng-ren** [listen1/listen1_desktop#441]
启动速度非常慢。如果需要安装测试配合，请联系rencheng11@icloud.com。定会支持

**Comment by listen1** [comment]
感谢反馈，已经增加了V2.21.0的mac M1版本更新
https://github.com/listen1/listen1_desktop/releases/tag/v2.21.0
请下载 listen1_2.21.0_mac_arm64.dmg 的链接
