### ISSUE TITLE
[Bug]Windows Desktop无法登录qq音乐

### ISSUE THREAD

**Issue by fbano-0619** [listen1/listen1_desktop#462]
在弹出网页后登录界面无变化
![Honeycam 2021-05-08 03-58-35](https://user-images.githubusercontent.com/80695112/117503536-a8be9080-afb3-11eb-8d92-f9eb4b4a2748.gif)

**Comment by listen1** [comment]
感谢反馈，能否按F12看一下console标签页中的报错信息？

**Comment by pigstrong9** [comment]
![image](https://user-images.githubusercontent.com/29220747/117529674-6cb71a00-b00b-11eb-8755-91b772ffe07f.png)

**Comment by pigstrong9** [comment]
map_userinfo这个对象是空的，用的是微信登录，QQ登录正常

**Comment by listen1** [comment]
已经查明原因，微信登录后的uin改写规则变化导致的登录不成功，已经修复了该bug
https://github.com/listen1/listen1_chrome_extension/commit/1cef6b3d15836fda724f0351d384608e5cfce98a

**Comment by fbano-0619** [comment]
![动画](https://user-images.githubusercontent.com/80695112/118937348-05d91f80-b980-11eb-93fd-74d4a97f0ce9.gif)
我更新后还是无法登录

**Comment by listen1** [comment]
请更新v2.21.5，应该是微信登录接口变化导致的问题。已经修复
