### ISSUE TITLE
[feature]字体大小调整

### ISSUE THREAD

**Issue by yujiangqaq** [listen1/listen1_desktop#472]
希望增加字体大小调整功能，现版本对高分屏设备似乎不太友好，尽管通过全屏的方法可以强行铺满整个屏幕，但是字体大小不会改变，看起来非常地费眼

**Comment by mikelxk** [comment]
你可以用ctrl+/-来调整缩放，应该能让高分屏的内容以你预想的方式显示

**Comment by yujiangqaq** [comment]
好吧，我一直没有发现这个快捷键...或许它也应该被添加到设置中的快捷键菜单

**Comment by listen1** [comment]
https://github.com/listen1/listen1_chrome_extension/commit/a7bb4804ca4f1d01b25f580bd933a3968b77b561
