### ISSUE TITLE
Windows 端使用 System Media Transport Controls API

### ISSUE THREAD

**Issue by Geeyun-JY3** [listen1/listen1_desktop#478]
应该是叫这个吧，从 [ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts/blob/main/docs/GSMTC-Support-And-Popular-Apps.md) 看回来的。最直观的的就是调节音量时出来的音量条右方会有个当前播放媒体信息卡片：
![](https://docs.microsoft.com/en-us/uwp/api/windows.media/images/smtc.png?view=winrt-20348)

- 相关文档：https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols

**Comment by mikelxk** [comment]
![image](https://user-images.githubusercontent.com/32220948/120112321-e1631b80-c1a7-11eb-819e-504ac43c731e.png)
listen1用mediaSession似乎已经使用了该api

**Comment by Geeyun-JY3** [comment]
这么说有 bug？我这边 v2.21.5 在 Windows 10 21H1 19043.1023 中并无媒体信息卡片。
是否需要更多信息？

**Comment by mikelxk** [comment]
你chrome或edge播放音乐有OSD嘛？

**Comment by Geeyun-JY3** [comment]
OSD 是指上面提到的媒体信息卡片吗？

**Comment by mikelxk** [comment]
是的

**Comment by Geeyun-JY3** [comment]
Chrome 和 Edge 都有的。Listen1 扩展在 Chrome 和 Edge 中播放音乐也都有的。

**Comment by mikelxk** [comment]
试试重新安装app？
或者我可以试着做一个electron新版本的listen1安装包给你试试？

**Comment by Geeyun-JY3** [comment]
之前重装过了。这个也试过了，好像还是不行……

**Comment by yujiangqaq** [comment]
好家伙，这里也有一个魂

**Comment by listen1** [comment]
请留一下系统版本和chrome版本方便测试，谢谢

**Comment by Geeyun-JY3** [comment]
Windows 10 系统版本在上面有：https://github.com/listen1/listen1_desktop/issues/478#issuecomment-851131141

Chrome 版本是指使用插件的 Chrome 版本吗？插件版并没有这个问题。
