### ISSUE TITLE
windows版的按钮图标是否可调整下？

### ISSUE THREAD

**Issue by oishi81** [listen1/listen1_desktop#480]
现有的根本看不出来是什么用途啊
我是win10 x64

**Comment by Geeyun-JY3** [comment]
说的是标题栏的那几个按钮对吧：#399

**Comment by oishi81** [comment]
如图，播放按钮，右上的设置按钮等等，都是不可识别。
我是下载的win10 x64 绿色最新版2.21.5
![image](https://user-images.githubusercontent.com/65519561/120876718-1080ef00-c5e5-11eb-8570-b64fbecb00f9.png)

**Comment by Geeyun-JY3** [comment]
你这好像是 bug 了，正常不是这样的，也不是什么调整下的事了。

**Comment by oishi81** [comment]
> 你这好像是 bug 了，正常不是这样的，也不是什么调整下的事了。

好的，而且我分别用了两台不同的电脑，都是这个现象。

**Comment by mikelxk** [comment]
用安装版试下吧
