### ISSUE TITLE
[bug] app打开后陷在这个界面无法操作

### ISSUE THREAD

**Issue by luc99hen** [listen1/listen1_desktop#500]
![image](https://user-images.githubusercontent.com/28707897/124086037-3e8e0d80-da83-11eb-89e3-945aeb2d6241.png)
安装后第一次打开正常，从GitHub Gist导入用户设置后，关闭应用第二次打开即出现这种情况。

**Comment by luc99hen** [comment]
![image](https://user-images.githubusercontent.com/28707897/124088802-e3114f00-da85-11eb-9e74-8dd4fc366705.png)
![image](https://user-images.githubusercontent.com/28707897/124088902-fc1a0000-da85-11eb-9be7-1820b35ba797.png)

顺着console的错误修改了这个配置（false -> true），解决了问题。

**Comment by listen1** [comment]
fixed in https://github.com/listen1/listen1_desktop/commit/f3d46d40908af055534fd9c47ced3ca6b5f0f636
