### ISSUE TITLE
问题和建议

### ISSUE THREAD

**Issue by QingW-7023** [listen1/listen1_desktop#506]
1.现在QQ的单曲搜不出来了，但可以搜歌单，也可以从歌单内进去播放。
2.现在浏览器应用越来越流行了，大佬要不要考虑下上架浏览器应用呢？😄️这不仅方便用户更新，还能完成很多特殊操作。
3.歌词在滚动的时候，如果能让上方和下方都出现渐淡消失的效果就好了，会更自然一些。
最后，像大佬致敬！

**Comment by yujiangqaq** [comment]
listen1一开始就是浏览器应用。。。支持chrome，Firefox

**Comment by QingW-7023** [comment]
> listen1一开始就是浏览器应用。。。支持chrome，Firefox

哈哈，这是我不知道的，入门得晚了。
最近我发现了油管音乐的Edge应用，真的有好多优势。比如同步方便、安装更新方便、启动关闭快速，还可以在应用上操作手势（用浏览器扩展实现的）……
经过微软对自己浏览器的大力强化（已经比Chrome更好了），Win11上又强化了视觉元素，所以现在的应用又好用又好看，真的不错。

**Comment by listen1** [comment]
qq搜索单曲问题已经处理，更换了请求qq服务器的接口地址，应该有所改善

浏览器应用的代码在另一个仓库

歌词渐淡消失的效果的建议我们已经加入开发计划中。

谢谢你的建议和反馈

**Comment by QingW-7023** [comment]
感谢告知！另外是我不查，不好意思，现在任何浏览器页面都可以安装到应用，只要在浏览器菜单里执行“将此页面作为应用安装”就好了。
感谢大佬们提供了这么优秀的软件！
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用


发件人: Listen 1 ***@***.***>
发送时间: Monday, July 19, 2021 5:21:04 AM
收件人: listen1/listen1_desktop ***@***.***>
抄送: 王清 ***@***.***>; State change ***@***.***>
主题: Re: [listen1/listen1_desktop] 问题和建议 (#506)


qq搜索单曲问题已经处理，更换了请求qq服务器的接口地址，应该有所改善

浏览器应用的代码在另一个仓库

歌词渐淡消失的效果的建议我们已经加入开发计划中。

谢谢你的建议和反馈

―
