### ISSUE TITLE
9-25 虾米不能用

### ISSUE THREAD

**Issue by AimLuo** [listen1/listen1_desktop#51]
win10 64位
另外能不能加上被禁的一些歌单。比如陈一发的童话镇

**Comment by gj3169** [comment]
![qq 20181111095928](https://user-images.githubusercontent.com/12198675/48308153-8a20df80-e598-11e8-8f74-9eab1ed30df7.png)

**1.8.0 windows版本，虾米搜索失效**
1、复现步骤：
1）打开软件首页，点击“精选歌单”-“虾米”，加载页面为空
2）打开“快速搜索”，搜索关键词（如“小幸运”），再点击“虾米”，一直加载
2、补充说明
1）其他数据源（网易、QQ音乐等）都正常。
2）Chrome浏览器打开虾米地址（http://www.xiami.com）正常
3）ping系统命令返回结果
```
PS C:\Users\xxxx> ping www.xiami.com

正在 Ping na61-na62.wagbridge.alibaba.taobao.com.gds.alibabadns.com [203.119.244.127] 具有 32 字节的数据:
来自 203.119.244.127 的回复: 字节=32 时间=40ms TTL=89
来自 203.119.244.127 的回复: 字节=32 时间=40ms TTL=89
来自 203.119.244.127 的回复: 字节=32 时间=40ms TTL=89
来自 203.119.244.127 的回复: 字节=32 时间=264ms TTL=89

203.119.244.127 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 40ms，最长 = 264ms，平均 = 96ms
```
4）机器IP：
IP：`124.202.*.*`  来自：北京市 BGP多线
5）win10 版本：1809，如下图所示：
![image](https://user-images.githubusercontent.com/12198675/48308176-25b25000-e599-11e8-87cf-ff7bd003f593.png)
