### ISSUE TITLE
本地音乐乱码

### ISSUE THREAD

**Issue by lawchou** [listen1/listen1_desktop#514]
添加本地音乐后出现乱码
![微信截图_20210722220406](https://user-images.githubusercontent.com/73280921/126653288-d443345f-2fab-4891-9faa-40dbcef704a3.png)
如上图所示，listen1版本为2.21.6

**Comment by lawchou** [comment]
[01.东风破.zip](https://github.com/listen1/listen1_desktop/files/6862811/01.zip)

**Comment by mikelxk** [comment]
https://github.com/Borewit/music-metadata/issues/164
在属性里面重新写一下标题就行了

**Comment by lawchou** [comment]
如果只有几首歌可以这样，我这里出现了几十首，都是这样，一首一首地改属性还是有点麻烦，能不能软件自动处理？我猜测是当属性为空，显示文件名的编码问题

**Comment by mikelxk** [comment]
我用mp3tag看了一下，你歌的tag是以中文编码再包了一层iso-8859-1的，的确不是utf-16编码的。
https://audio-tag-analyzer.netlify.app/
foobar和mp3tag似乎做了额外的处理，你要批量改的话我建议你可以看一下https://www.mydigitallife.net/how-to-auto-convert-mp3-id3-tag-charset-to-unicode-utf-8/ 
或者在右键详细信息里面随便改个字符windows就会以utf-16为格式保存。
我这儿很难改这个问题因为用的库已经把这个乱码string给转出来了

**Comment by lawchou** [comment]
我使用Mp3tag 实现了批量修改歌曲信息，有同样需求的朋友可以下载： https://xiazai.zol.com.cn/detail/37/366261.shtml
