### ISSUE TITLE
本地歌词乱码

### ISSUE THREAD

**Issue by hailhy** [listen1/listen1_desktop#515]
本地音乐添加后歌词全部乱码。
<img width="1036" alt="iShot2021-07-23 16 07 54" src="https://user-images.githubusercontent.com/83583051/126754236-e90dfc9d-fe15-4fb6-80f0-c70248ab0961.png">

**Comment by mikelxk** [comment]
请问你lrc文件的编码是什么 cjk？ gbk？
或者是文件自带的歌词？

**Comment by hailhy** [comment]
网易云自带的歌词  什么编码我不懂
[4 In Love-一千零一个愿望.lrc.zip](https://github.com/listen1/listen1_desktop/files/6869541/4.In.Love-.lrc.zip)

**Comment by mikelxk** [comment]
编码应该是gbk或者类似，pr: #516
