### ISSUE TITLE
mac 客户端，将歌曲添加到歌单逻辑有问题

### ISSUE THREAD

**Issue by SkyeSong38** [listen1/listen1_desktop#53]
在 mac 客户端上，将歌曲添加到歌单的时候，新添加的歌曲按正常逻辑应该出现在歌单的最上面呀。可是现在是出现在最下面，不知道是 mac 上的问题还是所有的都是这样。希望修改一下。

**Comment by listen1** [comment]
感谢反馈，这个逻辑确实有问题，会在下个版本(2.1)中修复

**Comment by listen1** [comment]
已经在2.1.1版本中修复
