### ISSUE TITLE
播放至54秒时卡住的问题

### ISSUE THREAD

**Issue by duzhor** [listen1/listen1_desktop#54]
问题描述:
        正常播放歌单, 概率出现某歌曲播放至54秒时卡住不动, 此时点暂停或播放无任何反应, 点上一曲或下一曲即正常播放, 但是依旧会概率卡住.
使用环境:
        Windows10. Listen 1 桌面版.

**Comment by listen1** [comment]
https://github.com/listen1/listen1_desktop/issues/24
