### ISSUE TITLE
界面能调整一下么，强迫症受不了啊，居然换行了

### ISSUE THREAD

**Issue by cethink** [listen1/listen1_desktop#564]
![image](https://user-images.githubusercontent.com/756512/134859674-d4435e6a-76c0-4171-9518-4613ab856448.png)

**Comment by listen1** [comment]
感谢反馈，窗口是可以支持调整宽度的，可以拉宽一点，当然后期我们尽量计算一下宽度保持一行显示。

**Comment by cethink** [comment]
拉宽也没用哦，不然我也不会反馈了🙄，你可以试试
