### ISSUE TITLE
导入浏览器扩展导出的歌单后，客户端崩溃了

### ISSUE THREAD

**Issue by EliYao** [listen1/listen1_desktop#587]
重新安装也无效，有办法清除导入的数据吗？
导入的数据来自：浏览器插件
导入到的客户端： Mac 版客户端
![image](https://user-images.githubusercontent.com/7480584/143545154-46296359-f48d-412a-b1d4-537262e8a134.png)

**Comment by mikelxk** [comment]
#500 
@listen1 Should we release a new version that include that fix?

**Comment by listen1** [comment]
> #500 @listen1 Should we release a new version that include that fix?

sure. my fault. I forgot release after fix it.

**Comment by leowy** [comment]
> > #500 @listen1 Should we release a new version that include that fix?
> 
> sure. my fault. I forgot release after fix it.

Are there any plans to release a new version？

**Comment by mikelxk** [comment]
https://github.com/listen1/listen1_desktop/releases/tag/v2.21.7
