### ISSUE TITLE
Mac端快捷键支持

### ISSUE THREAD

**Issue by jwei0701** [listen1/listen1_desktop#6]
赞！希望mac端可以支持快捷键播放/暂停，上/下一曲。

**Comment by doseeing** [comment]
有快捷键的功能，在关于页可以查看快捷键列表，不过是应用内不是系统全局的

**Comment by listen1** [comment]
有快捷键的功能，在关于页可以查看快捷键列表，不过是应用内不是系统全局的

**Comment by listen1** [comment]
#20 中有全局快捷键的支持，等待merge中
