### ISSUE TITLE
构建后网易云无法正常使用

### ISSUE THREAD

**Issue by ChuJian2** [listen1/listen1_desktop#608]
我先后在Arch和Windows下构建Listen1，但所得到的软件无法播放网易云的歌，也无法使用网易云搜索，请问是那儿出现了问题？

**Comment by HPDHaPiDog** [comment]
本人在ArchLinux上同样遇到了此问题
OS: Arch Linux x86_64
Kernel: 5.16.0-arch1-1 
本人使用了AUR  [AUR链接](https://aur.archlinux.org/packages/listen1-desktop/) 来快速构建
然而得到的Listen1版本无法访问网易云相关的内容（包括单曲和歌单，推荐）
不知道什么问题

**Comment by HPDHaPiDog** [comment]
另外，构建的时候是使用chrome扩展那里的来用electron构建
扩展可以用那么为什么electron不能用呢
我猜测有可能是两者内核（chromium和electron）不一样，然后导致了网易云方面返回的结果不一样
所以作者大大看看能不能解决这个问题吧

**Comment by mikelxk** [comment]
arch据我所知应该是自带了electron runtime
listen1现在的版本(v2.21.6)似乎用了`remote`来操作cookie，应该不能在electron14+上工作,
如果你想构建在electron14的话 推荐使用[v3版本](https://github.com/listen1/listen1_chrome_extension/tree/next/electron_src)

**Comment by ChuJian2** [comment]
> 

感谢答复，刚才试了构建在electron13下后，发现可以正常使用了。

**Comment by ChuJian2** [comment]
默认是使用了 electron16
