### ISSUE TITLE
下载windows版后，第一次打开导入歌单，然后就打不开了

### ISSUE THREAD

**Issue by on-create** [listen1/listen1_desktop#610]
![image](https://user-images.githubusercontent.com/69442367/149265039-9759ab62-114f-4c0e-86e4-db4bb10511ab.png)

**Comment by on-create** [comment]
这个怎么解决？

**Comment by on-create** [comment]
从github上导入歌单后，再点击退出，重新启动就会这样

**Comment by mikelxk** [comment]
参考#500 的解决办法

**Comment by mikelxk** [comment]
https://github.com/listen1/listen1_desktop/releases/tag/v2.21.7
