### ISSUE TITLE
请添加一个英语用户界面 | English

### ISSUE THREAD

**Issue by probonopd** [listen1/listen1_desktop#62]
请添加一个英语用户界面。Please add an English user interface.

![](https://github.com/AppImage/appimage.github.io/raw/f62240e52f3e274f976ff6de5c9291e50ca6b716/database/Listen_1/screenshot.png)

**Comment by listen1** [comment]
New version v2.1.0 support English.

How to change language ?
---

1. Click Settings icon in right top of application
2. Click English under Language or 语言

**Comment by probonopd** [comment]
Thank you. Can you make it use English by default if the system language is not Chinese? E.g., by looking at the `LANG` environment variable.

On my system:

```
me@host:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by listen1** [comment]
New version already support English/French, thanks for your support.

**Comment by listen1** [comment]
maybe there's bug if user system not install chinese font, so should detect user default language. reopen.
