### ISSUE TITLE
无法启动AppImage

### ISSUE THREAD

**Issue by shuizhongyu** [listen1/listen1_desktop#66]
运行Listen1_2.1.1_linux_x86_64.AppImage后：
报：(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
然后退出，无法启动，请问如何解决？

**Comment by listen1** [comment]
日志信息不影响启动，请注意状态栏右上角是否已经有Listen1的图标了。如果有了，请点击退出后重新启动
