### ISSUE TITLE
希望能改进一下随机播放功能

### ISSUE THREAD

**Issue by Kelnql** [listen1/listen1_desktop#665]
不知道listen1的随机播放是根据什么算法，打开随机播放后常常出现重复随机某几首歌的情况，而不是整个歌单都不重复地随机，我觉得体验感没有音乐软件的随机播放那么好，如果能稍微改进一下就更好啦！
祝：项目越来越好~

**Comment by piz-ewing** [comment]
` // TODO: shuffle algorithm instead of random
  nextIndexFn = () => Math.floor(Math.random() * this.playlist.length);`

出现这个问题的原因是，这里是真随机😄
并没有将已播放过的歌曲移出随机队列

我会试着去处理一下这个问题

**Comment by piz-ewing** [comment]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/78925867/163752226-f277c382-e5a1-43f0-9c7f-d9e754b29d2a.png">

另外发现一处bug
idx可能为 0 而导致返回-1

**Comment by mikelxk** [comment]
#835
