### ISSUE TITLE
请问能不能添加删除歌单的功能，有的歌单不更新想删除的话无法删除

### ISSUE THREAD

**Issue by Bosco0059** [listen1/listen1_desktop#704]

**Comment by mikelxk** [comment]
你可以在编辑里 选择删除歌单

**Comment by Bosco0059** [comment]
不好意思，我没写明白，不是手机端，是pc端无法删除歌单

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月26日(周四) 中午11:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [listen1/listen1_desktop] 请问能不能添加删除歌单的功能，有的歌单不更新想删除的话无法删除 (Issue #704)




 
你可以在编辑里 选择删除歌单

**Comment by mikelxk** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/32220948/170411164-05a2f7b1-a1bc-4e25-8751-13f2465bef2f.png">

**Comment by Bosco0059** [comment]
已经得到解决，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "listen1/listen1_desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [listen1/listen1_desktop] 请问能不能添加删除歌单的功能，有的歌单不更新想删除的话无法删除 (Issue #704)
