### ISSUE TITLE
【建议】自动跳过歌单中的无效歌曲

### ISSUE THREAD

**Issue by rockbenben** [listen1/listen1_desktop#74]
歌单中有些歌曲已经失效，不能播放。播放器会一直停在那，需要手动跳过。
希望增加个逻辑，**一定时间内（10 秒）未成功链接歌曲服务器，自动跳过，播放下一首歌曲**

**Comment by KingGeorgeWang** [comment]
我觉得也许可以添加一个逻辑，一首歌曲指向多个链接，一个链接失效切换成另一个~

**Comment by listen1** [comment]
很好的建议，我们会在后续开发中加入此功能

**Comment by liuzhaowei55** [comment]
十分迫切的需求了，灰色歌曲越来越多，经常卡带。

**Comment by listen1** [comment]
已经添加了自动跳过的功能
