### ISSUE TITLE
歌词显示异常

### ISSUE THREAD

**Issue by hundanlzl** [listen1/listen1_desktop#76]
![2019-01-24-22-47-04](https://user-images.githubusercontent.com/40019188/51686074-9dd1d300-202a-11e9-961e-c1e7bbbdc737.png)

**Comment by silascript** [comment]
这好像是某网站（好像是酷狗）歌词问题。用foobar也会出现这问题，换个网下歌词就正常。

**Comment by listen1** [comment]
某些歌词使用了逐字精确的格式，所以会有此问题，已经在v2.17.0版本解决了该问题
