### ISSUE TITLE
能设置倍速播放吗

### ISSUE THREAD

**Issue by jdAction** [listen1/listen1_desktop#792]

**Comment by jessejyang** [comment]
同求

**Comment by jdAction** [comment]
这个我想用global speed对插件进行加速的时候发现没法对插件进行加速，希望作者可以增加这个功能。

**Comment by jdAction** [comment]
更换了liten1的浏览器插件，从浏览器插件的issue中找我的包直接用。作者不知道是进小黑屋了吗，好久没在线了
