### ISSUE TITLE
1.2mac版快捷键只有在Listen1软件处于on focus时才有效，处于后台就不能控制了

### ISSUE THREAD

**Issue by ancanglee** [listen1/listen1_desktop#8]
如题，快捷键只有在Listen1软件窗口处于on focus时才有效，如果软件在后台，快捷键就不起作用了，求支持全局快捷键，就算软件在后台也可以直接控制，键盘党求支持，辛苦各位码农了！

**Comment by listen1** [comment]
#20 中有全局快捷键的，等待merge中

**Comment by listen1** [comment]
感谢反馈，在最新版本中已经增加了全局快捷键支持
