### ISSUE TITLE
点x关闭后状态栏没有图标，无法调处程序

### ISSUE THREAD

**Issue by Heinzyang** [listen1/listen1_desktop#82]
ubuntu18.04，点x关闭之后，程序仍在运行，且状态栏无listen1程序，无法调出。

**Comment by listen1** [comment]
可以看看最上面的状态栏中是否有listen1的小图标，可能有点不显眼。

**Comment by Heinzyang** [comment]
> 可以看看最上面的状态栏中是否有listen1的小图标，可能有点不显眼。

我可以确定是没有的，可能是我装了一些桌面美化插件的原因？
