### ISSUE TITLE
listen1 linux版不支持播放ape格式的本地文件；本地同名歌词lrc文件无法与音乐关联

### ISSUE THREAD

**Issue by LittleSeaSir** [listen1/listen1_desktop#837]
在本地音乐添加了ape格式的音乐后无法播放，但mp3，wav,flac格式均正常。
播放本地音乐时，与音乐同名的歌词lrc文件无法直接识别并使用，且没有可以使之关联的按钮入口。

**Comment by mikelxk** [comment]
> 在本地音乐添加了ape格式的音乐后无法播放，但mp3，wav,flac格式均正常。

似乎播放ape就不是web原生支持的,我打算之后把ape文件选择给取消掉

>播放本地音乐时，与音乐同名的歌词lrc文件无法直接识别并使用，且没有可以使之关联的按钮入口。

能给下歌词和音乐的文件嘛

**Comment by LittleSeaSir** [comment]
> 播放本地音乐时，与音乐同名的歌词lrc文件无法直接识别并使用，且没有可以使之关联的按钮入口。

第二条，我后来发现了，是我以为音乐和歌词已经同名了，但实际并不是同名的，我的问题对不起了！
但是仍然建议添加一个能自己动手关联本地音乐和本地歌词的按钮。
