### ISSUE TITLE
Mac DMG包开发者验证问题

### ISSUE THREAD

**Issue by wayne0332** [listen1/listen1_desktop#84]
作为一个码农,当然知道怎样把osx 10.12的应用安装限制干掉,但是经历过装破解软件被盗dota号之后,再也不关这个限制了,希望作者打包时能搞个认证开发者的账号打包一下(可以把源码下下来自己打包,可以直接通过验证,但是懒癌病犯了)

**Comment by listen1** [comment]
你好，因为认证开发者可能需要实名的一些信息，而软件本身又有一些争议，所以暂时只能用这种匿名形式发布了。谢谢您对listen1的支持

CAFEBABE <notifications@github.com> 于2019年2月21日周四 下午3:18写道：

**Comment by wayne0332** [comment]
好吧,了解作者的难处了,那我拉下来自己打包吧,麻烦了.
(P.S. CAFEBABE->0xCAFEBABE->class file?!连小组群都没人知道的梗竟然在这碰到知音)
