### ISSUE TITLE
windows V2.1.2版本QQ音乐无法播放

### ISSUE THREAD

**Issue by kangbb** [listen1/listen1_desktop#85]
# 问题
windows V2.1.2版本QQ音乐无法播放，音乐时长和已播放时长均显示00:00。希望有空可以修复一下~

**Comment by Pekary** [comment]
同遇到，大概是昨天或者前天出现的，qq音乐官网可以正常播放

**Comment by vlazhuv** [comment]
是呀
上周还是可以的
今天打开就不能播放QQ音乐了

**Comment by listen1** [comment]
插件版已经修复qq音乐无法播放的问题，桌面版也会尽快升级。谢谢反馈
