### ISSUE TITLE
搜索歌曲，qq音乐和所有音乐展示不出来

### ISSUE THREAD

**Issue by lzq-flame** [listen1/listen1_desktop#861]

**Comment by mikelxk** [comment]
请问下是最新版本嘛？

**Comment by lzq-flame** [comment]
不好意思，我又删了重下可以了！感谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月26日 16:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [listen1/listen1_desktop] 搜索歌曲，qq音乐和所有音乐展示不出来 (Issue #861) |

请问下是最新版本嘛？
