### ISSUE TITLE
关于electron updater如今已经被弃用的问题

### ISSUE THREAD

**Issue by jinzhongjia** [listen1/listen1_desktop#874]
我尝试在nixos上打包listen1,然后在程序运行时会在控制台输出：
```bash
checkForUpdatesAndNotify called, downloadPromise is null
```
经查阅后发现是由electron updater已经被弃用导致的，可以考虑其他工具来进行检测更新

**Comment by mikelxk** [comment]
Electron updater并没有被弃用 https://github.com/electron-userland/electron-builder/releases/tag/electron-updater%405.3.0
这一行的输出是因为代码运行在debug mode下
