### ISSUE TITLE
网易云音乐的歌单无法添加

### ISSUE THREAD

**Issue by kituo** [listen1/listen1_desktop#89]
这是我尝试添加的网易云音乐歌单：https://music.163.com/#/playlist?id=313138840
我看见12月有人已经提出了这个问题，而且作者也在最后回复新版本已经修复。
这个是作者在回复中留下的歌单地址：http://music.163.com/#/playlist?id=2194233968
（他们在最新版中都无法添加）
![snipaste_2019-02-28_16-40-11](https://user-images.githubusercontent.com/30134945/53553505-d0ff0900-3b78-11e9-9b74-c0bef8f9e97a.png)

**Comment by listen1** [comment]
你好，问题确实存在，更新了一次2.1.4的桌面版，插件版请下载最新的zip包。谢谢你的反馈

谭斟 <notifications@github.com> 于2019年2月28日周四 下午4:51写道：

**Comment by lizy0327** [comment]
解决此问题的方法：
1.在浏览器（本人使用的chrome83）添加插件版的linten1
2.在插件版listen1里导入网易云音乐的歌单
3.然后通过插件版的listen1的设置备份歌单，歌单会以json的格式下载到本地
4.然后通过客户端导入备份的歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单，导入备份会覆盖现有歌单
