### ISSUE TITLE
桌面歌词会跟着鼠标

### ISSUE THREAD

**Issue by caolib** [listen1/listen1_desktop#915]
刚开始用还是挺正常的，之后突然桌面歌词一直跟着鼠标移动，更难受的是鼠标点击没用了，应该是歌词挡住的原因，只能先锁屏然后歌词才会消失

**Comment by wangtiandi** [comment]
+1  左键按下后，没有弹起，右键再按下。然后歌词就一直跟着鼠标了。
松开按键没有作用。
需要移动到任务栏 找到状态栏图标 右键退出才行。
