### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by Enzo-feifei** [listen1/listen1_desktop#92]
Adolf@HFeizzZ MINGW64 /f/listen1_desktop (master)
$ git@github.com:listen1/listen1_desktop.git
bash: git@github.com:listen1/listen1_desktop.git: No such file or directory

Adolf@HFeizzZ MINGW64 /f/listen1_desktop (master)
$ git submodule update --init --recursive
Submodule 'app/listen1_chrome_extension' (git@github.com:listen1/listen1_chrome_extension.git) registered for path 'app/listen1_chrome_extension'
Cloning into 'F:/listen1_desktop/app/listen1_chrome_extension'...
Submodule path 'app/listen1_chrome_extension': checked out '762e912087aa42833c6cb9fb862a30194a114520'
![Up

**Comment by listen1** [comment]
第一个命令似乎出错了，应该是 
```bash
$ git clone git@github.com:listen1/listen1_desktop.git
```
