### ISSUE TITLE
新建歌单按钮异常

### ISSUE THREAD

**Issue by xu-h** [listen1/listen1_desktop#94]
打开歌词界面的情况下，如下图红框，新建歌单按钮只有一半有效，有效区域恰好是与歌词区域的重叠部分
![listen1-issue](https://user-images.githubusercontent.com/10136940/53804032-620f1f00-3f81-11e9-9016-c7456cd0b810.png)
无效区域长按能够拖动窗口，疑似z-index设置错误导致出现鼠标穿透
(ver2.1.5, linux x64)

**Comment by listen1** [comment]
确认为bug，应该是可拖动区域的配置问题。

**Comment by listen1** [comment]
你好，已经在v2.17.0版本中修复了该问题，谢谢您的反馈
