### ISSUE TITLE
BiliBili 视频只能播放 P1

### ISSUE THREAD

**Issue by scientificworld** [listen1/listen1_desktop#956]
分P视频只能播放P1，后面的无法播放

比如 [东方同人音乐博物馆总集篇【例大祭15前统合】](https://www.bilibili.com/video/BV1FW411k76N) 这类视频

希望能增加播放其他分P的功能，比如可以做成显示为专辑的形式

**Comment by 4ft35t** [comment]
我也被这个问题困扰了一会，找到了正确的用法。

搜索结果默认是__“单曲”__，点一下最右边的 __“歌单”__，再点具体的条目进去就是完整播放列表。

![1](https://github.com/listen1/listen1_desktop/assets/2051049/3d356d3c-dbf2-487d-be8f-9afa21496b26)

![image](https://github.com/listen1/listen1_desktop/assets/2051049/d62e5dcd-a207-4545-8c23-92889fc908c9)

**Comment by scientificworld** [comment]
这个可以 感谢！
